-- ============================================================
-- CLEANUP SCRIPT: Remove all objects and roles associated with
-- the Snowflake Intelligence quickstart (DASH_DB_SI)
-- ============================================================
-- WARNING: This script is DESTRUCTIVE and IRREVERSIBLE.
-- Review carefully before executing.
-- ============================================================

USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

-- 1. Drop Cortex Agent
DROP AGENT IF EXISTS DASH_DB_SI.RETAIL.MARKETINGAGENT;

-- 2. Drop Cortex Search Service (must drop before dependent dynamic tables)
DROP CORTEX SEARCH SERVICE IF EXISTS DASH_DB_SI.RETAIL.CAMPAIGN_SEARCH;

-- 3. Drop Semantic View
DROP SEMANTIC VIEW IF EXISTS DASH_DB_SI.RETAIL.SEMANTIC_VIEW;

-- 4. Drop Dynamic Tables
DROP DYNAMIC TABLE IF EXISTS DASH_DB_SI.RETAIL.ENRICHED_MARKETING_INTELLIGENCE;

-- 5. Drop Stored Procedure
DROP PROCEDURE IF EXISTS DASH_DB_SI.RETAIL.SEND_EMAIL(VARCHAR, VARCHAR, VARCHAR);

-- 6. Drop Git Repository (must drop before API integration)
DROP GIT REPOSITORY IF EXISTS DASH_DB_SI.RETAIL.SNOWFLAKE_LABS_SFGUIDE_SI_REPO;

-- 7. Drop Tables
DROP TABLE IF EXISTS DASH_DB_SI.RETAIL.MARKETING_CAMPAIGN_METRICS;
DROP TABLE IF EXISTS DASH_DB_SI.RETAIL.PRODUCTS;
DROP TABLE IF EXISTS DASH_DB_SI.RETAIL.SALES;
DROP TABLE IF EXISTS DASH_DB_SI.RETAIL.SOCIAL_MEDIA;
DROP TABLE IF EXISTS DASH_DB_SI.RETAIL.SUPPORT_CASES;

-- 8. Drop Stages
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SEMANTIC_MODELS;
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SWT_MARKETING_DATA_STAGE;
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SWT_PRODUCTS_DATA_STAGE;
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SWT_SALES_DATA_STAGE;
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SWT_SOCIAL_MEDIA_DATA_STAGE;
DROP STAGE IF EXISTS DASH_DB_SI.RETAIL.SWT_SUPPORT_DATA_STAGE;

-- 9. Drop File Format
DROP FILE FORMAT IF EXISTS DASH_DB_SI.RETAIL.SWT_CSVFORMAT;

-- 10. Drop Databases (cascades schemas and remaining objects)
DROP DATABASE IF EXISTS DASH_DB_SI;
DROP DATABASE IF EXISTS SNOWFLAKE_INTELLIGENCE;

-- 11. Drop Warehouse
DROP WAREHOUSE IF EXISTS DASH_WH_SI;

-- 12. Drop Integrations (requires ACCOUNTADMIN)
USE ROLE ACCOUNTADMIN;
DROP INTEGRATION IF EXISTS SNOWFLAKE_LABS_SI_GIT_API_INTEGRATION;
DROP INTEGRATION IF EXISTS EMAIL_INTEGRATION;

-- 13. Revoke account-level privileges and drop role
REVOKE CREATE WAREHOUSE ON ACCOUNT FROM ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
REVOKE CREATE DATABASE ON ACCOUNT FROM ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
REVOKE CREATE INTEGRATION ON ACCOUNT FROM ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
DROP ROLE IF EXISTS SNOWFLAKE_INTELLIGENCE_ADMIN;
