-- <copyright file="ssis_read_baseline_data.sql" company="Snowflake Inc">
--        Copyright (c) 2019-2025 Snowflake Inc. All rights reserved.
-- </copyright>

-- ==========================================================================
-- DESCRIPTION: The READ_BASELINE_DATA(ssis_log_file_stage_path VARCHAR, control_flow_stage_path VARCHAR) 
--   Stored procedure to load data generated by the instrumentation of SSIS packages into the
--   PUBLIC.BASELINE_TABLE_METRICS_LOG table.
--   The "ssis_log_file_stage_path" argument specify the path to a stage file that contains the execution 
--   log of the package which is used to track data flow data. The second argument "control_flow_stage_path" specifies
--   the path to a stage file with the information about the execution of the control flow.
-- ==========================================================================  

CREATE OR REPLACE PROCEDURE PUBLIC.READ_BASELINE_DATA(ssis_log_file_stage_path VARCHAR, control_flow_stage_path VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
   -- Step #1: Load data for data flow execution for SSIS log file

   -- Temporary table with the fields of the ssis log file
   CREATE or REPLACE TEMPORARY TABLE TMP_TBL (
    "#Fields: event" VARCHAR,
    computer VARCHAR,	
    "operator" VARCHAR,	
    "source" VARCHAR,	
    "sourceid"	VARCHAR, 
    "executionid" VARCHAR,	
    starttime	VARCHAR,
    endtime VARCHAR,	
    datacode VARCHAR,	
    databytes VARCHAR,	
    message VARCHAR);

   CREATE OR REPLACE FILE FORMAT CSV16 
      TYPE=CSV 
      FIELD_DELIMITER = ','   
      RECORD_DELIMITER = '\n'  
      SKIP_HEADER = 1 
      ENCODING='UTF-16' 
      SKIP_BYTE_ORDER_MARK=true 
      SKIP_BLANK_LINES = true;

   COPY INTO TMP_TBL FROM :ssis_log_file_stage_path
      FILE_FORMAT=(FORMAT_NAME='csv16');

    INSERT INTO  PUBLIC.BASELINE_TABLE_METRICS_LOG (
                task_name ,
                task_guid ,
                component_name ,
                component_output_name ,
                rowcount,
                kind,
                timestamp)

    select dataflow_name as task_name,
           task_guid,
           from_component,
           from_component_output as component_output_name,
           total_rows as rowcount,
           'df' as kind,
           timestamp
    from (
      
    SELECT  t."source" as dataflow_name,
            t."sourceid" as task_guid,
            REGEXP_REPLACE(split_part(message, ':', 11), 'Paths.([^.]*)\\.([^]]*).*$','\\1') AS from_component,
            split_part(message, ':', 6) AS to_component,   
            REGEXP_REPLACE(split_part(message, ':', 11), 'Paths.([^.]*)\\.([^]]*).*$','\\2') AS from_component_output,
            split_part(message, ':', 9)::number as row_count,
            to_timestamp_ntz(t.endtime, 'mm/dd/yyyy hh:mi:ss pm') as timestamp,
            from_component || '/' || from_component_output || '/' || to_component as key,
            sum(row_count) over (partition by key order by key)  as total_rows
    FROM TMP_TBL t
    WHERE t."#Fields: event" = 'OnPipelineRowsSent'
    QUALIFY  row_number() over (partition by key order by key)  = 1); 
   
   DROP TABLE TMP_TBL;

   -- Step #2: Load data for control flow execution for SSIS log file
    
   CREATE TEMPORARY TABLE TMP_TBL (
        TaskName varchar,
        guid varchar,
        schemaname varchar,
        tablename varchar,
        rowcount int,
        timestamp timestamp_ntz);
    
   COPY INTO TMP_TBL FROM :control_flow_stage_path
       FILE_FORMAT=(TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1 TIMESTAMP_FORMAT = 'mm/dd/yyyy hh:mi:ss pm');
   INSERT INTO  PUBLIC.BASELINE_TABLE_METRICS_LOG (
                    task_name ,
                    task_guid ,
                    schema_name,
                    table_name,
                    rowcount,
                    kind,
                    timestamp)
    SELECT taskname, SUBSTR(guid, 1, 40) AS task_guid, schemaname, tablename, rowcount,'cf', timestamp from TMP_TBL                ;
END;
$$;