-- Snowflake Iceberg V3 Comprehensive Guide
-- Script 05: Create Governance Objects
-- =====================================

USE ROLE ACCOUNTADMIN;
USE DATABASE FLEET_ANALYTICS_DB;
USE WAREHOUSE FLEET_ANALYTICS_WH;

-- ============================================
-- ROLES AND PERMISSIONS
-- ============================================

-- Create analyst role with limited access
CREATE ROLE IF NOT EXISTS FLEET_ANALYST;
GRANT USAGE ON DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ANALYST;
GRANT USAGE ON SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ANALYST;
GRANT USAGE ON SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT USAGE ON SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;

-- Grant SELECT on regular tables
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;

-- Grant SELECT on Iceberg tables (separate object type in Snowflake)
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ANALYST;
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;

-- Grant SELECT on Dynamic Tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ANALYST;

GRANT USAGE ON WAREHOUSE FLEET_ANALYTICS_WH TO ROLE FLEET_ANALYST;

-- Create engineer role with full access
CREATE ROLE IF NOT EXISTS FLEET_ENGINEER;
GRANT USAGE ON DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;
GRANT ALL ON SCHEMA FLEET_ANALYTICS_DB.RAW TO ROLE FLEET_ENGINEER;
GRANT ALL ON SCHEMA FLEET_ANALYTICS_DB.CURATED TO ROLE FLEET_ENGINEER;
GRANT ALL ON SCHEMA FLEET_ANALYTICS_DB.ANALYTICS TO ROLE FLEET_ENGINEER;

-- Grant INGEST LINEAGE for external lineage registration
-- This allows the streaming script to register data lineage from IoT sources
-- See: https://docs.snowflake.com/en/user-guide/external-lineage
GRANT INGEST LINEAGE ON ACCOUNT TO ROLE ACCOUNTADMIN;
GRANT INGEST LINEAGE ON ACCOUNT TO ROLE FLEET_ENGINEER;

-- Grant on regular tables
GRANT ALL ON ALL TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;
GRANT ALL ON FUTURE TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;

-- Grant on Iceberg tables
GRANT ALL ON ALL ICEBERG TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;
GRANT ALL ON FUTURE ICEBERG TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;

-- Grant on Dynamic Tables
GRANT ALL ON ALL DYNAMIC TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;
GRANT ALL ON FUTURE DYNAMIC TABLES IN DATABASE FLEET_ANALYTICS_DB TO ROLE FLEET_ENGINEER;

GRANT USAGE ON WAREHOUSE FLEET_ANALYTICS_WH TO ROLE FLEET_ENGINEER;

-- Create admin role
CREATE ROLE IF NOT EXISTS FLEET_ADMIN;
GRANT ROLE FLEET_ENGINEER TO ROLE FLEET_ADMIN;
GRANT ROLE FLEET_ANALYST TO ROLE FLEET_ADMIN;

-- ============================================
-- MASKING POLICIES
-- ============================================

-- Create schema for policies
CREATE SCHEMA IF NOT EXISTS FLEET_ANALYTICS_DB.POLICIES;

-- Masking policy for PII - Names
CREATE OR REPLACE MASKING POLICY POLICIES.PII_NAME_MASK AS (val STRING) 
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('FLEET_ADMIN', 'FLEET_ENGINEER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() = 'FLEET_ANALYST' THEN 
            CONCAT(LEFT(val, 2), REPEAT('*', LENGTH(val) - 4), RIGHT(val, 2))
        ELSE REPEAT('*', 8)
    END;

-- Masking policy for PII - Email
CREATE OR REPLACE MASKING POLICY POLICIES.PII_EMAIL_MASK AS (val STRING) 
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('FLEET_ADMIN', 'FLEET_ENGINEER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() = 'FLEET_ANALYST' THEN 
            CONCAT(
                LEFT(val, 2),
                REPEAT('*', POSITION('@' IN val) - 3),
                SUBSTRING(val, POSITION('@' IN val))
            )
        ELSE '****@****.***'
    END;

-- Masking policy for PII - Phone
CREATE OR REPLACE MASKING POLICY POLICIES.PII_PHONE_MASK AS (val STRING) 
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('FLEET_ADMIN', 'FLEET_ENGINEER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() = 'FLEET_ANALYST' THEN 
            CONCAT(LEFT(val, 6), '****', RIGHT(val, 2))
        ELSE '+1-***-***-****'
    END;

-- Apply masking policies to VEHICLE_REGISTRY PII columns
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY 
    MODIFY COLUMN DRIVER_NAME SET MASKING POLICY POLICIES.PII_NAME_MASK;
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY 
    MODIFY COLUMN DRIVER_EMAIL SET MASKING POLICY POLICIES.PII_EMAIL_MASK;
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY 
    MODIFY COLUMN DRIVER_PHONE SET MASKING POLICY POLICIES.PII_PHONE_MASK;

-- ============================================
-- DATA METRIC FUNCTIONS (DMFs)
-- ============================================

-- DMF: Check for valid geographic coordinates
CREATE OR REPLACE DATA METRIC FUNCTION RAW.CHECK_VALID_COORDINATES(
    arg_t TABLE(LATITUDE FLOAT, LONGITUDE FLOAT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) 
    FROM arg_t
    WHERE LATITUDE < -90 OR LATITUDE > 90 
       OR LONGITUDE < -180 OR LONGITUDE > 180
       OR LATITUDE IS NULL OR LONGITUDE IS NULL
$$;

-- DMF: Check for valid vehicle IDs (must match pattern VH-XXXX)
CREATE OR REPLACE DATA METRIC FUNCTION RAW.CHECK_VALID_VEHICLE_ID(
    arg_t TABLE(VEHICLE_ID VARCHAR)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) 
    FROM arg_t
    WHERE NOT REGEXP_LIKE(VEHICLE_ID, '^VH-[0-9]{4}$')
       OR VEHICLE_ID IS NULL
$$;

-- DMF: Check for engine temperature anomalies
CREATE OR REPLACE DATA METRIC FUNCTION RAW.CHECK_ENGINE_TEMP_ANOMALY(
    arg_t TABLE(ENGINE_TEMP_F FLOAT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) 
    FROM arg_t
    WHERE ENGINE_TEMP_F < 50 OR ENGINE_TEMP_F > 300
       OR ENGINE_TEMP_F IS NULL
$$;

-- DMF: Check for null variant data
CREATE OR REPLACE DATA METRIC FUNCTION RAW.CHECK_NULL_VARIANT(
    arg_t TABLE(VARIANT_COL VARIANT)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) 
    FROM arg_t
    WHERE VARIANT_COL IS NULL
       OR VARIANT_COL = 'null'::VARIANT
       OR OBJECT_KEYS(VARIANT_COL) IS NULL
$$;

-- DMF: Check for duplicate records
CREATE OR REPLACE DATA METRIC FUNCTION RAW.CHECK_DUPLICATE_READINGS(
    arg_t TABLE(VEHICLE_ID VARCHAR, READING_TIMESTAMP TIMESTAMP_NTZ)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT(*) - COUNT(DISTINCT CONCAT(VEHICLE_ID, '|', READING_TIMESTAMP::VARCHAR))
    FROM arg_t
$$;

-- ============================================
-- APPLY DMFs TO TABLES
-- ============================================

-- Apply coordinate check to VEHICLE_LOCATIONS
ALTER ICEBERG TABLE RAW.VEHICLE_LOCATIONS 
    ADD DATA METRIC FUNCTION RAW.CHECK_VALID_COORDINATES 
    ON (LATITUDE, LONGITUDE);

-- Apply vehicle ID check to multiple tables
ALTER ICEBERG TABLE RAW.SENSOR_READINGS 
    ADD DATA METRIC FUNCTION RAW.CHECK_VALID_VEHICLE_ID 
    ON (VEHICLE_ID);

ALTER ICEBERG TABLE RAW.VEHICLE_LOCATIONS 
    ADD DATA METRIC FUNCTION RAW.CHECK_VALID_VEHICLE_ID 
    ON (VEHICLE_ID);

-- Apply engine temp check to SENSOR_READINGS
ALTER ICEBERG TABLE RAW.SENSOR_READINGS 
    ADD DATA METRIC FUNCTION RAW.CHECK_ENGINE_TEMP_ANOMALY 
    ON (ENGINE_TEMP_F);

-- Apply null variant check to tables with VARIANT columns
ALTER ICEBERG TABLE RAW.VEHICLE_TELEMETRY_STREAM 
    ADD DATA METRIC FUNCTION RAW.CHECK_NULL_VARIANT 
    ON (TELEMETRY_DATA);

ALTER ICEBERG TABLE RAW.MAINTENANCE_LOGS 
    ADD DATA METRIC FUNCTION RAW.CHECK_NULL_VARIANT 
    ON (LOG_DATA);

-- ============================================
-- TAGS FOR CLASSIFICATION
-- ============================================

-- Create custom tags
CREATE TAG IF NOT EXISTS POLICIES.DATA_SENSITIVITY 
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data sensitivity classification';

CREATE TAG IF NOT EXISTS POLICIES.PII_TYPE 
    ALLOWED_VALUES 'NAME', 'EMAIL', 'PHONE', 'ADDRESS', 'SSN', 'FINANCIAL'
    COMMENT = 'Type of personally identifiable information';

CREATE TAG IF NOT EXISTS POLICIES.DATA_DOMAIN 
    ALLOWED_VALUES 'TELEMETRY', 'MAINTENANCE', 'LOCATION', 'DRIVER', 'VEHICLE'
    COMMENT = 'Business domain for the data';

-- Apply tags to tables
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY SET TAG 
    POLICIES.DATA_SENSITIVITY = 'CONFIDENTIAL',
    POLICIES.DATA_DOMAIN = 'DRIVER';

ALTER ICEBERG TABLE RAW.VEHICLE_TELEMETRY_STREAM SET TAG 
    POLICIES.DATA_SENSITIVITY = 'INTERNAL',
    POLICIES.DATA_DOMAIN = 'TELEMETRY';

ALTER ICEBERG TABLE RAW.VEHICLE_LOCATIONS SET TAG 
    POLICIES.DATA_SENSITIVITY = 'INTERNAL',
    POLICIES.DATA_DOMAIN = 'LOCATION';

ALTER ICEBERG TABLE RAW.MAINTENANCE_LOGS SET TAG 
    POLICIES.DATA_SENSITIVITY = 'INTERNAL',
    POLICIES.DATA_DOMAIN = 'MAINTENANCE';

ALTER ICEBERG TABLE RAW.SENSOR_READINGS SET TAG 
    POLICIES.DATA_SENSITIVITY = 'INTERNAL',
    POLICIES.DATA_DOMAIN = 'TELEMETRY';

-- Apply PII tags to columns
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_NAME SET TAG POLICIES.PII_TYPE = 'NAME';
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_EMAIL SET TAG POLICIES.PII_TYPE = 'EMAIL';
ALTER ICEBERG TABLE RAW.VEHICLE_REGISTRY MODIFY COLUMN DRIVER_PHONE SET TAG POLICIES.PII_TYPE = 'PHONE';

-- ============================================
-- VERIFY GOVERNANCE SETUP
-- ============================================

SHOW MASKING POLICIES IN DATABASE FLEET_ANALYTICS_DB;
SHOW DATA METRIC FUNCTIONS IN DATABASE FLEET_ANALYTICS_DB;
SHOW TAGS IN DATABASE FLEET_ANALYTICS_DB;

-- Show tags applied to a table
SELECT * FROM TABLE(INFORMATION_SCHEMA.TAG_REFERENCES('FLEET_ANALYTICS_DB.RAW.VEHICLE_REGISTRY', 'TABLE'));

SELECT 'Governance objects created!' AS STATUS;
