schema_version: 1.0
project_id: MIGRATION_PROJECT_f1079059_003b_42af_8832_553332d80bd2
project_name: sql-server-migration
source_language: SqlServer
source_connection: tastybytesdb
created_by: aaguilarmoya
created_at: 2026-05-26T16:34:43.1860000Z
cloud_project_id: MIGRATION_PROJECT_f1079059_003b_42af_8832_553332d80bd2
snowflake_connection: summit_hol_test
etl_source_path: /Users/aaguilarmoya/projects/sfguide-scai-e2e-ssis-migration/etl
project_type: full_migration
enable_cloud_status: true
