--Create the warehouse that the connector will use to ingest data into Snowflake
CREATE OR REPLACE WAREHOUSE IDENTIFIER('"SERVICENOW_CONNECTOR_WH"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 60 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

--Create the warehouse that will manage the connector SERVICENOW_WAREHOUSE
CREATE OR REPLACE WAREHOUSE IDENTIFIER('"SERVICENOW_WAREHOUSE"') COMMENT = '' WAREHOUSE_SIZE = 'X-Small' AUTO_RESUME = true AUTO_SUSPEND = 60 ENABLE_QUERY_ACCELERATION = false WAREHOUSE_TYPE = 'STANDARD' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';
