-- ============================================================
-- BONUS: TABLE & AGENT RBAC FOR CORTEX AGENTS
-- ============================================================
-- If you're extending this solution to use Cortex Agents,
-- grant tenant roles access to the underlying data and agents.
-- Run as ACCOUNTADMIN in a Snowsight worksheet.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ---- Warehouse access (needed to run queries) ----
GRANT USAGE ON WAREHOUSE COCO_WH TO ROLE COCO_TENANT_ALPHA;
GRANT USAGE ON WAREHOUSE COCO_WH TO ROLE COCO_TENANT_BETA;

-- ---- Database + schema access ----
GRANT USAGE ON DATABASE RETAILBOT_DB TO ROLE COCO_TENANT_ALPHA;
GRANT USAGE ON SCHEMA RETAILBOT_DB.SUPPORT TO ROLE COCO_TENANT_ALPHA;

GRANT USAGE ON DATABASE RETAILBOT_DB TO ROLE COCO_TENANT_BETA;
GRANT USAGE ON SCHEMA RETAILBOT_DB.SUPPORT TO ROLE COCO_TENANT_BETA;

-- ---- Table-level SELECT grants ----
GRANT SELECT ON TABLE RETAILBOT_DB.SUPPORT.SUPPORT_TICKETS TO ROLE COCO_TENANT_ALPHA;
GRANT SELECT ON TABLE RETAILBOT_DB.SUPPORT.PRODUCT_CATALOG TO ROLE COCO_TENANT_ALPHA;

GRANT SELECT ON TABLE RETAILBOT_DB.SUPPORT.SUPPORT_TICKETS TO ROLE COCO_TENANT_BETA;
GRANT SELECT ON TABLE RETAILBOT_DB.SUPPORT.PRODUCT_CATALOG TO ROLE COCO_TENANT_BETA;

-- ---- Cortex Agent access ----
GRANT USAGE ON CORTEX AGENT RETAILBOT_DB.SUPPORT.RETAILBOT TO ROLE COCO_TENANT_ALPHA;
GRANT USAGE ON CORTEX AGENT RETAILBOT_DB.SUPPORT.RETAILBOT TO ROLE COCO_TENANT_BETA;

-- ---- Cortex Search service access (if agent uses search) ----
GRANT USAGE ON CORTEX SEARCH SERVICE RETAILBOT_DB.SUPPORT.SUPPORT_SEARCH TO ROLE COCO_TENANT_ALPHA;
GRANT USAGE ON CORTEX SEARCH SERVICE RETAILBOT_DB.SUPPORT.SUPPORT_SEARCH TO ROLE COCO_TENANT_BETA;

-- ---- Verify grants ----
SHOW GRANTS TO ROLE COCO_TENANT_ALPHA;
SHOW GRANTS TO ROLE COCO_TENANT_BETA;
