USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.OrderHeader (
    OrderID INT IDENTITY(1,1) ORDER NOT NULL,
    CustomerID INT NOT NULL,
    TruckID INT NOT NULL,
    OrderDate TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__OrderHead__Order__5165187F' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    CompletedAt TIMESTAMP_NTZ(3) NULL,
    OrderStatus VARCHAR(20) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL DEFAULT ('Pending') /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__OrderHead__Order__52593CB8' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    TotalAmount NUMBER(38, 4) NOT NULL DEFAULT ((0.00)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__OrderHead__Total__534D60F1' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    TipAmount NUMBER(38, 4) NULL DEFAULT ((0.00)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__OrderHead__TipAm__5441852A' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    PaymentMethod VARCHAR(30) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    OrderNotes NVARCHAR(500) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    CreatedAt TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__OrderHead__Creat__5535A963' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    ModifiedAt TIMESTAMP_NTZ(3) NULL
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;