-- Setup script for Online ML - Feature Store and Inference
-- Co-authored with CoCo
-- ============================================================
-- Run this in a Snowsight SQL worksheet before importing the notebook.
-- ============================================================

-- Database and schema
CREATE DATABASE IF NOT EXISTS RECOMMEND_DB;
CREATE SCHEMA IF NOT EXISTS RECOMMEND_DB.RECOMMEND;

-- Warehouse for SQL and Python workloads
CREATE WAREHOUSE IF NOT EXISTS RECOMMEND_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Compute pool for SPCS inference service
CREATE COMPUTE POOL IF NOT EXISTS RECOMMEND_CPU_POOL
    MIN_NODES = 1
    MAX_NODES = 2
    INSTANCE_FAMILY = CPU_X64_S;

-- Required privilege for public SPCS inference endpoints
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE ACCOUNTADMIN;

-- Feature Store producer and consumer roles
CREATE ROLE IF NOT EXISTS FS_PRODUCER_ROLE;
CREATE ROLE IF NOT EXISTS FS_CONSUMER_ROLE;

GRANT USAGE ON DATABASE RECOMMEND_DB TO ROLE FS_PRODUCER_ROLE;
GRANT USAGE ON DATABASE RECOMMEND_DB TO ROLE FS_CONSUMER_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE RECOMMEND_DB TO ROLE FS_PRODUCER_ROLE;
GRANT USAGE ON SCHEMA RECOMMEND_DB.RECOMMEND TO ROLE FS_PRODUCER_ROLE;
GRANT USAGE ON SCHEMA RECOMMEND_DB.RECOMMEND TO ROLE FS_CONSUMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE, CREATE TAG ON SCHEMA RECOMMEND_DB.RECOMMEND TO ROLE FS_PRODUCER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RECOMMEND_DB.RECOMMEND TO ROLE FS_CONSUMER_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA RECOMMEND_DB.RECOMMEND TO ROLE FS_CONSUMER_ROLE;
GRANT USAGE ON WAREHOUSE RECOMMEND_WH TO ROLE FS_PRODUCER_ROLE;
GRANT USAGE ON WAREHOUSE RECOMMEND_WH TO ROLE FS_CONSUMER_ROLE;

GRANT ROLE FS_PRODUCER_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE FS_CONSUMER_ROLE TO ROLE ACCOUNTADMIN;

-- ============================================================
-- Cleanup: Uncomment below to drop all objects created by this script
-- ============================================================
-- DROP ROLE IF EXISTS FS_CONSUMER_ROLE;
-- DROP ROLE IF EXISTS FS_PRODUCER_ROLE;
-- DROP COMPUTE POOL IF EXISTS RECOMMEND_CPU_POOL;
-- DROP WAREHOUSE IF EXISTS RECOMMEND_WH;
-- DROP DATABASE IF EXISTS RECOMMEND_DB;
