#!/usr/bin/env python3
"""Render and post every pull request comment the deploy workflow produces.

The report files this reads come from an artifact built by a run over pull request
code, so every string in them is attacker-chosen. They are treated purely as data:
each field is rendered through lib.mdsafe before it enters a comment body, no field
influences control flow, and report files are opened by fixed names inside the
artifact directory with the resolved path asserted to stay within it.

Usage:
    post_comments.py {validation-failures,informational,quickstart-staged,journey-staged}

Environment:
    GITHUB_TOKEN       token used to post the comment
    GITHUB_REPOSITORY  owner/repo, supplied by Actions
    PR_NUMBER          pull request to comment on
    ARTIFACT_DIR       directory the validation artifact was downloaded into
    QUICKSTART_NAME    quickstart-staged only
    LANGUAGE           quickstart-staged only
    GUIDE_NAME         journey-staged only
    HEAD_SHA           staging kinds only
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from lib import gh, mdsafe, validate

STAGING_HOST = "https://placeholder.example.com"
TEST_ENV_NOTE = "> **Note:** This is a test environment. AEM upload and publish steps are skipped."
SIGNATURE = "---\n*Generated by GitHub Actions*"

LARGE_FILE_ADVICE = (
    "You have two options: \n 1. Reduce the file size(s) before merging (best for "
    "images); or \n 2. Move your file(s) into a folder beginning with an underscore "
    "(e.g., `_large_files/`). Note that in this case, your file will NOT be uploaded "
    "to snowflake.com, and you will have to [link to it directly](https://docs.github.com"
    "/en/repositories/working-with-files/using-files/getting-permanent-links-to-files)."
)
LANGUAGE_DEFAULT_MESSAGE = (
    "Invalid or missing language detected. Allowed: en, es, it, fr, de, ja, ko, pt_br"
)


class Reports:
    """Reads report JSON from the artifact, refusing to escape its directory."""

    def __init__(self, root: Path) -> None:
        self._root = root.resolve()

    def read(self, name: str) -> dict[str, Any] | None:
        """Return a report object, or None if it is absent or unusable."""
        if "/" in name or "\\" in name:
            msg = f"report name must be a bare filename: {name!r}"
            raise ValueError(msg)

        candidate = self._root / name
        if candidate.is_symlink():
            print(f"::warning::ignoring symlinked report: {name}")
            return None

        resolved = candidate.resolve()
        if not resolved.is_relative_to(self._root) or not resolved.is_file():
            return None
        try:
            data = json.loads(resolved.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"::warning::ignoring unreadable report {name}: {exc}")
            return None
        return data if isinstance(data, dict) else None


def _file_bullet(entry: object) -> str:
    return mdsafe.code(entry)


def _folder_renames(report: dict[str, Any] | None) -> str | None:
    if not report or report.get("type") != "folder_rename":
        return None
    renames = mdsafe.as_list(report.get("renames"))
    if not renames:
        return None
    listing = mdsafe.bullets(
        renames,
        lambda item: (
            f"{mdsafe.code(item.get('old_folder'))} → {mdsafe.code(item.get('new_folder'))}"
            if isinstance(item, dict)
            else mdsafe.code(item)
        ),
    )
    return f"### 📁 Folder Rename Detected\n\n{mdsafe.text(report.get('message'))}\n\n{listing}"


def _large_files(report: dict[str, Any] | None) -> str | None:
    if not report:
        return None
    files = mdsafe.as_list(report.get("files"))
    if not files:
        return None
    listing = mdsafe.bullets(files, _file_bullet)
    return (
        f"### 📦 Large Files Detected\n\nFiles larger than 1MB found:\n\n"
        f"{listing}\n\n{LARGE_FILE_ADVICE}"
    )


def _multiple_markdown(report: dict[str, Any] | None) -> str | None:
    if not report or report.get("type") != "multiple_markdown_files":
        return None
    errors = mdsafe.as_list(report.get("errors"))
    if not errors:
        return None

    def render(item: object) -> str:
        if not isinstance(item, dict):
            return mdsafe.code(item)
        files = mdsafe.as_list(item.get("files"))
        nested = "\n".join(f"  - {mdsafe.code(name)}" for name in files[: mdsafe.MAX_ITEMS])
        return f"**{mdsafe.text(item.get('folder'))}** ({len(files)} files):\n{nested}"

    listing = mdsafe.bullets(errors, render)
    message = mdsafe.text(report.get("message"))
    return f"### 📄 Multiple Markdown Files Detected\n\n{message}\n\n{listing}"


def _language(report: dict[str, Any] | None) -> str | None:
    if not report or report.get("type") != "language":
        return None
    entries = mdsafe.as_list(report.get("files"))
    listing = mdsafe.bullets(
        entries,
        lambda item: (
            f"{mdsafe.code(item.get('file'))}: {mdsafe.code(item.get('language'))}"
            if isinstance(item, dict)
            else mdsafe.code(item)
        ),
    )
    message = mdsafe.text(report.get("message") or LANGUAGE_DEFAULT_MESSAGE)
    return f"### 🌐 Language Validation Failed\n\n{message}\n\n{listing}"


def _issue_bullet(item: object, field: str, separator: str) -> str:
    if not isinstance(item, dict):
        return mdsafe.code(item)
    values = mdsafe.as_list(item.get(field))[: mdsafe.MAX_ITEMS]
    rendered = separator.join(mdsafe.code(value) for value in values) or "(none)"
    return f"{mdsafe.code(item.get('file'))}: {rendered}"


def _issue_list(report: dict[str, Any], field: str, separator: str) -> str:
    entries = mdsafe.as_list(report.get("issues"))
    return mdsafe.bullets(entries, lambda item: _issue_bullet(item, field, separator))


def _categories(report: dict[str, Any] | None) -> str | None:
    if report is None:
        return None
    heading = "### 🏷️ Category Syntax Validation Failed"
    if not mdsafe.as_list(report.get("issues")):
        return f"{heading}\n\nCategory syntax is invalid."
    blurb = "Expected categories like 'snowflake-site:taxonomy/x/y'."
    return f"{heading}\n\n{blurb}\n\n{_issue_list(report, 'invalid', ', ')}"


def _frontmatter(report: dict[str, Any] | None) -> str | None:
    if report is None:
        return None
    heading = "### 📄 Frontmatter Validation Failed"
    if not mdsafe.as_list(report.get("issues")):
        return f"{heading}\n\nFrontmatter id check failed."
    blurb = "Frontmatter id must be slugified and match file and folder."
    return f"{heading}\n\n{blurb}\n\n{_issue_list(report, 'errors', '; ')}"


def _profanity(report: dict[str, Any] | None, heading: str, blurb: str, footer: str) -> str | None:
    if report is None:
        return None
    if report.get("error"):
        return f"{heading}\n\n{mdsafe.text(report.get('error'))}"
    issues = mdsafe.as_list(report.get("issues"))
    if not issues:
        return None
    listing = mdsafe.bullets(
        issues,
        lambda item: (
            f"{mdsafe.code(item.get('file'))}: "
            f"{mdsafe.join_inline(mdsafe.as_list(item.get('words')))}"
            if isinstance(item, dict)
            else mdsafe.code(item)
        ),
    )
    return f"{heading}\n\n{blurb}\n\n{listing}{footer}"


def _files_notice(report: dict[str, Any] | None, expected: str, heading: str) -> str | None:
    if not report or report.get("type") != expected:
        return None
    files = mdsafe.as_list(report.get("files"))
    if not files:
        return None
    listing = mdsafe.bullets(files, _file_bullet)
    return f"{heading}\n\n{mdsafe.text(report.get('message'))}\n\n{listing}"


def failure_body(reports: Reports) -> str | None:
    """Aggregate every blocking validation failure into one comment."""
    sections = [
        _folder_renames(reports.read("folder-rename-error.json")),
        _large_files(reports.read("large-files-error.json")),
        _multiple_markdown(reports.read("multiple-md-error.json")),
        _language(reports.read("validation-error.json")),
        _categories(reports.read("categories-error.json")),
        _frontmatter(reports.read("frontmatter-error.json")),
        _profanity(
            reports.read("profanity-report.json"),
            "### 🚫 Profanity Check Failed",
            "Abusive words detected:",
            "",
        ),
    ]
    present = [section for section in sections if section]
    if not present:
        return None
    joined = "\n\n---\n\n".join(present)
    return f"## ⚠️ Validation Failed\n\n{joined}\n\nPlease fix the issues above before merging."


def informational_body(reports: Reports) -> str | None:
    """Aggregate the non-blocking notices into one comment."""
    sections = [
        _profanity(
            reports.read("profanity-report.json"),
            "### Profanity Check Notice",
            "Potentially inappropriate words were detected in the following files:",
            "\n\nPlease review and consider revising if appropriate.",
        ),
        _files_notice(
            reports.read("non-image-assets-warning.json"),
            "non_image_assets",
            "### Non-Image Files in Assets Folder",
        ),
        _files_notice(
            reports.read("non-markdown-root-info.json"),
            "non_markdown_root",
            "### Non-Markdown Files in Quickstart Root",
        ),
    ]
    present = [section for section in sections if section]
    if not present:
        return None
    joined = "\n\n---\n\n".join(present)
    return (
        f"## Helpful Information\n\n{joined}\n\nThese are informational messages and "
        "will not block your PR from being merged."
    )


def quickstart_body() -> str:
    """Announce the staging location for one quickstart."""
    name = validate.guide_name(os.environ.get("QUICKSTART_NAME"))
    lang = validate.language(os.environ.get("LANGUAGE") or validate.DEFAULT_LANGUAGE)
    head_sha = validate.sha40(os.environ.get("HEAD_SHA"))
    url = f"{STAGING_HOST}/{lang}/developers/guides/{name}-{head_sha}"
    return (
        f"## Staging Preview (Test Environment)\n\n"
        f"**Quickstart:** `{name}`\n**Language:** {lang}\n\n"
        f"**Preview URL (placeholder):** {url}\n\n{TEST_ENV_NOTE}\n\n{SIGNATURE}"
    )


def journey_body() -> str:
    """Announce the staging location for one journey guide."""
    name = validate.guide_name(os.environ.get("GUIDE_NAME"))
    head_sha = validate.sha40(os.environ.get("HEAD_SHA"))
    url = f"{STAGING_HOST}/en/developers/guides/{name}-{head_sha}"
    return (
        f"## Journey Guide Staging Preview (Test Environment)\n\n"
        f"**Guide:** `{name}`\n\n"
        f"**Preview URL (placeholder):** {url}\n\n{TEST_ENV_NOTE}\n\n{SIGNATURE}"
    )


def build_body(kind: str) -> str | None:
    """Return the comment body for `kind`, or None when there is nothing to say."""
    reports = Reports(Path(os.environ.get("ARTIFACT_DIR", "artifact")))
    builders = {
        "validation-failures": lambda: failure_body(reports),
        "informational": lambda: informational_body(reports),
        "quickstart-staged": quickstart_body,
        "journey-staged": journey_body,
    }
    return builders[kind]()


def main() -> int:
    """Build the requested comment and post it, if there is anything to post."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "kind",
        choices=["validation-failures", "informational", "quickstart-staged", "journey-staged"],
    )
    kind = parser.parse_args().kind

    repo = validate.repo_full_name(os.environ.get("GITHUB_REPOSITORY"))
    number = validate.pr_number(os.environ.get("PR_NUMBER"))

    body = build_body(kind)
    if body is None:
        print(f"No {kind} content to report; not commenting.")
        return 0

    client = gh.GitHub(os.environ.get("GITHUB_TOKEN", ""))
    client.post(f"/repos/{repo}/issues/{number}/comments", {"body": mdsafe.cap_body(body)})
    print(f"Posted {kind} comment to #{number}.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (gh.GitHubError, validate.ValidationError, ValueError) as error:
        print(f"::error::{error}", file=sys.stderr)
        sys.exit(1)
