USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.Customer (
    CustomerID INT IDENTITY(1,1) ORDER NOT NULL,
    CustomerGUID VARCHAR NOT NULL DEFAULT (UUID_STRING()) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Customer__Custom__4BAC3F29' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    FirstName NVARCHAR(100) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    LastName NVARCHAR(100) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    Email VARCHAR(255) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    PhoneNumber VARCHAR(20) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    PreferredCityID INT NULL,
    LoyaltyPoints INT NOT NULL DEFAULT ((0)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Customer__Loyalt__4CA06362' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    MemberSince DATE NOT NULL DEFAULT (CURRENT_DATE()) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Customer__Member__4D94879B' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    IsActive BOOLEAN NOT NULL DEFAULT true,
    CreatedAt TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Customer__Create__4F7CD00D' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    ModifiedAt TIMESTAMP_NTZ(3) NULL
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;