USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.EmployeeShift (
    ShiftID INT IDENTITY(1,1) ORDER NOT NULL,
    EmployeeName NVARCHAR(200) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    TruckID INT NOT NULL,
    ShiftDate DATE NOT NULL,
    StartTime TIMESTAMP_NTZ(3) NOT NULL,
    EndTime TIMESTAMP_NTZ(3) NOT NULL,
    HoursWorked NUMERIC(17, 6) NULL,
    Role VARCHAR(50) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL DEFAULT ('Cook') /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__EmployeeSh__Role__5CD6CB2B' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    HourlyRate NUMBER(38, 4) NOT NULL,
    CreatedAt TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__EmployeeS__Creat__5DCAEF64' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;