USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.Inventory (
    InventoryID INT IDENTITY(1,1) ORDER NOT NULL,
    TruckID INT NOT NULL,
    IngredientName NVARCHAR(200) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    QuantityOnHand DECIMAL(10, 2) NOT NULL DEFAULT ((0.00)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Inventory__Quant__59FA5E80' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    UnitOfMeasure VARCHAR(20) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    ReorderLevel DECIMAL(10, 2) NOT NULL DEFAULT ((10.00)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__Inventory__Reord__5AEE82B9' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    ExpirationDate DATE NULL,
    SupplierNotes NVARCHAR(500) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    LastRestocked TIMESTAMP_NTZ(3) NULL
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;