-- ============================================================
-- Cortex AI Cost Dashboard - Setup
-- ============================================================
-- This script is designed to be run with context set externally:
--   snow sql -f setup.sql --connection <conn> --role <role> \
--     --warehouse <wh> --database <db> --schema <schema>
-- OR via snowflake_sql_execute with USE statements prepended.
-- All objects are created in the current database.schema context.
-- ============================================================

CREATE DATABASE IF NOT EXISTS {{DATABASE}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA}};

CREATE OR REPLACE TABLE CORTEX_AI_UNIFIED_COSTS (
    USAGE_DATE DATE,
    SERVICE_CATEGORY VARCHAR(50),
    SERVICE_NAME VARCHAR(100),
    MODEL_NAME VARCHAR(100),
    CREDITS NUMBER(38,9),
    TOKENS NUMBER(38,0),
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    CACHE_READ_TOKENS NUMBER(38,0),
    CACHE_WRITE_TOKENS NUMBER(38,0),
    REQUEST_COUNT NUMBER(38,0),
    COST_USD NUMBER(38,6),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USAGE_DATE, SERVICE_CATEGORY, SERVICE_NAME, MODEL_NAME)
);

 
CREATE OR REPLACE TABLE CORTEX_AISQL_USAGE (
    USAGE_TIME TIMESTAMP_TZ,
    MODEL_NAME VARCHAR,
    FUNCTION_NAME VARCHAR,
    TOKEN_CREDITS NUMBER(38,9),
    TOKENS NUMBER(38,0),
    QUERY_ID VARCHAR PRIMARY KEY,
    QUERY_TAG VARCHAR,
    USER_ID NUMBER(38,0),
    WAREHOUSE_ID NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_ANALYST_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    USERNAME VARCHAR DEFAULT 'SYSTEM',
    CREDITS NUMBER(38,9),
    REQUEST_COUNT NUMBER(18,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (START_TIME, USERNAME)
);

CREATE OR REPLACE TABLE CORTEX_DOCUMENT_PROCESSING_USAGE (
    QUERY_ID VARCHAR PRIMARY KEY,
    CREDITS_USED FLOAT,
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    FUNCTION_NAME VARCHAR,
    MODEL_NAME VARCHAR,
    OPERATION_NAME VARCHAR,
    PAGE_COUNT NUMBER(38,0),
    DOCUMENT_COUNT NUMBER(38,0),
    FEATURE_COUNT NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_FINE_TUNING_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    MODEL_NAME VARCHAR,
    TOKEN_CREDITS NUMBER(38,9),
    TOKENS NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (START_TIME, MODEL_NAME)
);


CREATE OR REPLACE TABLE CORTEX_FUNCTIONS_QUERY_USAGE (
    QUERY_ID VARCHAR PRIMARY KEY,
    WAREHOUSE_ID NUMBER(38,0),
    MODEL_NAME VARCHAR,
    FUNCTION_NAME VARCHAR,
    TOKENS NUMBER(38,0),
    TOKEN_CREDITS NUMBER(38,9),
    START_TIME TIMESTAMP_TZ,
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_PROVISIONED_THROUGHPUT_USAGE (
    PROVISIONED_THROUGHPUT_ID VARCHAR,
    AI_SERVICE VARCHAR(11),
    INTERVAL_START_TIME TIMESTAMP_TZ,
    INTERVAL_END_TIME TIMESTAMP_TZ,
    CLOUD_SERVICE_PROVIDER VARCHAR,
    MODEL_NAME VARCHAR,
    TERM_START_DATE DATE,
    TERM_END_DATE DATE,
    PTU_COUNT NUMBER(38,0),
    PTU_CREDITS NUMBER(38,9),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROVISIONED_THROUGHPUT_ID, INTERVAL_START_TIME)
);

CREATE OR REPLACE TABLE CORTEX_REST_API_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    REQUEST_ID VARCHAR PRIMARY KEY,
    MODEL_NAME VARCHAR,
    TOKENS NUMBER(38,0),
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    USER_ID NUMBER(38,0),
    INFERENCE_REGION VARCHAR,
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_SEARCH_DAILY_USAGE (
    USAGE_DATE TIMESTAMP_TZ,
    DATABASE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    SERVICE_NAME VARCHAR,
    SERVICE_ID NUMBER(38,0),
    CONSUMPTION_TYPE VARCHAR(17),
    CREDITS NUMBER(38,9),
    MODEL_NAME VARCHAR,
    TOKENS NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USAGE_DATE, SERVICE_ID, CONSUMPTION_TYPE)
);

CREATE OR REPLACE TABLE CORTEX_SEARCH_SERVING_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    DATABASE_NAME VARCHAR,
    SCHEMA_NAME VARCHAR,
    SERVICE_NAME VARCHAR,
    SERVICE_ID NUMBER(38,0),
    CREDITS NUMBER(38,9),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (START_TIME, SERVICE_ID)
);

CREATE OR REPLACE TABLE DOCUMENT_AI_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    CREDITS_USED NUMBER(38,9),
    QUERY_ID VARCHAR PRIMARY KEY,
    OPERATION_NAME VARCHAR(26),
    PAGE_COUNT NUMBER(38,0),
    DOCUMENT_COUNT NUMBER(38,0),
    FEATURE_COUNT NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_CODE_CLI_USAGE (
    USER_ID NUMBER(38,0),
    REQUEST_ID VARCHAR PRIMARY KEY,
    PARENT_REQUEST_ID VARCHAR,
    USAGE_TIME TIMESTAMP_TZ,
    TOKEN_CREDITS NUMBER(38,9),
    TOKENS NUMBER(38,0),
    MODEL_NAME VARCHAR,
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    CACHE_READ_TOKENS NUMBER(38,0),
    CACHE_WRITE_TOKENS NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_CODE_SNOWSIGHT_USAGE (
    USER_ID NUMBER(38,0),
    REQUEST_ID VARCHAR PRIMARY KEY,
    PARENT_REQUEST_ID VARCHAR,
    USAGE_TIME TIMESTAMP_TZ,
    TOKEN_CREDITS NUMBER(38,9),
    TOKENS NUMBER(38,0),
    MODEL_NAME VARCHAR,
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    CACHE_READ_TOKENS NUMBER(38,0),
    CACHE_WRITE_TOKENS NUMBER(38,0),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORTEX_AGENT_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    USER_ID NUMBER(38,0),
    USER_NAME VARCHAR,
    FULL_NAME VARCHAR,
    REQUEST_ID VARCHAR PRIMARY KEY,
    PARENT_REQUEST_ID VARCHAR,
    AGENT_DATABASE_NAME VARCHAR,
    AGENT_SCHEMA_NAME VARCHAR,
    AGENT_NAME VARCHAR,
    TOKEN_CREDITS NUMBER(38,9),
    COST_USD NUMBER(38,6),
    TOKENS NUMBER(38,0),
    MODEL_NAME VARCHAR,
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SNOWFLAKE_INTELLIGENCE_USAGE (
    START_TIME TIMESTAMP_TZ,
    END_TIME TIMESTAMP_TZ,
    USER_ID NUMBER(38,0),
    USER_NAME VARCHAR,
    FULL_NAME VARCHAR,
    REQUEST_ID VARCHAR PRIMARY KEY,
    PARENT_REQUEST_ID VARCHAR,
    SNOWFLAKE_INTELLIGENCE_NAME VARCHAR,
    AGENT_DATABASE_NAME VARCHAR,
    AGENT_SCHEMA_NAME VARCHAR,
    AGENT_NAME VARCHAR,
    TOKEN_CREDITS NUMBER(38,9),
    COST_USD NUMBER(38,6),
    TOKENS NUMBER(38,0),
    MODEL_NAME VARCHAR,
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REST_API_TOKEN_RATES (
    MODEL_NAME VARCHAR(100),
    INPUT_RATE_PER_1M NUMBER(10,4),
    OUTPUT_RATE_PER_1M NUMBER(10,4),
    EFFECTIVE_START_DATE DATE NOT NULL,
    EFFECTIVE_END_DATE DATE NOT NULL,
    DISCOUNT_PCT NUMBER(5,2) DEFAULT 33,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_NAME, EFFECTIVE_START_DATE)
);

MERGE INTO REST_API_TOKEN_RATES tgt
USING (
    SELECT * FROM VALUES
        ('claude-3-5-sonnet', 3.00, 15.00, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('deepseek-r1', 1.35, 5.40, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.1-405b', 2.40, 2.40, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.1-70b', 0.72, 0.72, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.1-8b', 0.22, 0.22, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.2-1b', 0.10, 0.10, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.2-3b', 0.15, 0.15, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama3.3-70b', 0.72, 0.72, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('llama4-maverick', 0.24, 0.97, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('mistral-large', 4.00, 12.00, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('mistral-large2', 2.00, 6.00, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('mistral-7b', 0.15, 0.20, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('openai-gpt-oss-120b', 0.15, 0.60, '2025-01-01'::DATE, '2099-12-31'::DATE, 33),
        ('snowflake-llama-3.3-70b', 0.72, 0.72, '2025-01-01'::DATE, '2099-12-31'::DATE, 33)
    AS t(MODEL_NAME, INPUT_RATE, OUTPUT_RATE, START_DT, END_DT, DISC_PCT)
) src ON tgt.MODEL_NAME = src.MODEL_NAME AND tgt.EFFECTIVE_START_DATE = src.START_DT
WHEN MATCHED THEN UPDATE SET tgt.INPUT_RATE_PER_1M = src.INPUT_RATE, tgt.OUTPUT_RATE_PER_1M = src.OUTPUT_RATE, tgt.DISCOUNT_PCT = src.DISC_PCT
WHEN NOT MATCHED THEN INSERT (MODEL_NAME, INPUT_RATE_PER_1M, OUTPUT_RATE_PER_1M, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, DISCOUNT_PCT)
    VALUES (src.MODEL_NAME, src.INPUT_RATE, src.OUTPUT_RATE, src.START_DT, src.END_DT, src.DISC_PCT);

CREATE OR REPLACE TABLE CREDIT_BASE_RATES (
    SERVICE_TIER VARCHAR(15) NOT NULL,
    REGION_TYPE VARCHAR(10) NOT NULL,
    BASE_RATE_PER_CREDIT NUMBER(10,4) NOT NULL,
    TIER_DISCOUNT_PCT NUMBER(5,2) NOT NULL DEFAULT 0,
    EFFECTIVE_START_DATE DATE NOT NULL,
    EFFECTIVE_END_DATE DATE NOT NULL DEFAULT '2099-12-31'::DATE,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SERVICE_TIER, REGION_TYPE, EFFECTIVE_START_DATE)
);
--insert your customers credit rate below
MERGE INTO CREDIT_BASE_RATES tgt
USING (
    SELECT * FROM VALUES
        ('AI_SERVICES', 'GLOBAL',   2.00, 3, '2026-04-01'::DATE, '2099-12-31'::DATE),
        ('AI_SERVICES', 'REGIONAL', 2.20, 3, '2026-04-01'::DATE, '2099-12-31'::DATE),
        ('STANDARD',    'ANY',      {{CREDIT_RATE}}, 0, '2026-04-01'::DATE, '2099-12-31'::DATE) --insert your customers credit rate here
    AS t(TIER, REGION, RATE, DISC_PCT, START_DT, END_DT)
) src ON tgt.SERVICE_TIER = src.TIER AND tgt.REGION_TYPE = src.REGION AND tgt.EFFECTIVE_START_DATE = src.START_DT
WHEN MATCHED THEN UPDATE SET tgt.BASE_RATE_PER_CREDIT = src.RATE, tgt.TIER_DISCOUNT_PCT = src.DISC_PCT, tgt.EFFECTIVE_END_DATE = src.END_DT
WHEN NOT MATCHED THEN INSERT (SERVICE_TIER, REGION_TYPE, BASE_RATE_PER_CREDIT, TIER_DISCOUNT_PCT, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE)
    VALUES (src.TIER, src.REGION, src.RATE, src.DISC_PCT, src.START_DT, src.END_DT);

-- Historical rates (no tier discount before 2026-04-01) --insert your customers credit rate below
INSERT INTO CREDIT_BASE_RATES (SERVICE_TIER, REGION_TYPE, BASE_RATE_PER_CREDIT, TIER_DISCOUNT_PCT, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE) VALUES ('STANDARD', 'ANY', {{HISTORICAL_CREDIT_RATE}}, 0, '2025-01-01'::DATE, '2026-03-31'::DATE);--insert your customers credit rate here

CREATE OR REPLACE TABLE USER_AI_COSTS (
    USER_NAME VARCHAR,
    FULL_NAME VARCHAR,
    USAGE_DATE DATE,
    USAGE_TIME TIMESTAMP_TZ,
    SERVICE_CATEGORY VARCHAR(50),
    SERVICE_NAME VARCHAR,
    MODEL_NAME VARCHAR,
    TOKENS NUMBER(38,0),
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    CACHE_READ_TOKENS NUMBER(38,0),
    CACHE_WRITE_TOKENS NUMBER(38,0),
    CREDITS NUMBER(38,9),
    COST_USD NUMBER(38,6),
    QUERY_ID VARCHAR,
    DURATION_MS NUMBER(38,0),
    QUERY_TEXT VARCHAR(1000),
    LAST_REFRESHED TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (QUERY_ID, SERVICE_NAME)
);

 
CREATE OR REPLACE PROCEDURE REFRESH_CORTEX_AI_COSTS(DAYS_BACK INT DEFAULT 7)
RETURNS VARIANT
LANGUAGE SQL
AS
'
DECLARE
    result OBJECT DEFAULT OBJECT_CONSTRUCT();
    rows_affected INT;
    region_type VARCHAR;
    cross_region_value VARCHAR;
BEGIN
    SHOW PARAMETERS LIKE ''CORTEX_ENABLED_CROSS_REGION'' IN ACCOUNT;
    LET rs RESULTSET := (SELECT "value" AS VAL FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
    LET cur CURSOR FOR rs;
    cross_region_value := ''DISABLED'';
    FOR row_var IN cur DO
        cross_region_value := row_var.VAL;
    END FOR;
    IF (cross_region_value IN (''ANY_REGION'', ''AWS_GLOBAL'', ''GCP_GLOBAL'', ''AZURE_GLOBAL'')) THEN
        region_type := ''GLOBAL'';
    ELSE
        region_type := ''REGIONAL'';
    END IF;

    -- 1. CORTEX_AISQL_USAGE (incremental by QUERY_ID)
    MERGE INTO CORTEX_AISQL_USAGE tgt
    USING (
        SELECT USAGE_TIME, MODEL_NAME, FUNCTION_NAME, TOKEN_CREDITS, TOKENS, QUERY_ID, QUERY_TAG, USER_ID, WAREHOUSE_ID
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AISQL_USAGE_HISTORY
        WHERE USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.QUERY_ID = src.QUERY_ID
    WHEN NOT MATCHED THEN INSERT (USAGE_TIME, MODEL_NAME, FUNCTION_NAME, TOKEN_CREDITS, TOKENS, QUERY_ID, QUERY_TAG, USER_ID, WAREHOUSE_ID)
        VALUES (src.USAGE_TIME, src.MODEL_NAME, src.FUNCTION_NAME, src.TOKEN_CREDITS, src.TOKENS, src.QUERY_ID, src.QUERY_TAG, src.USER_ID, src.WAREHOUSE_ID);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_AISQL_USAGE'', rows_affected);

    -- 2. CORTEX_ANALYST_USAGE (incremental by START_TIME, USERNAME)
    MERGE INTO CORTEX_ANALYST_USAGE tgt
    USING (
        SELECT START_TIME, END_TIME, COALESCE(USERNAME, ''SYSTEM'') AS USERNAME, CREDITS, REQUEST_COUNT
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.START_TIME = src.START_TIME AND tgt.USERNAME = src.USERNAME
    WHEN MATCHED THEN UPDATE SET tgt.END_TIME = src.END_TIME, tgt.CREDITS = src.CREDITS, tgt.REQUEST_COUNT = src.REQUEST_COUNT, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, USERNAME, CREDITS, REQUEST_COUNT)
        VALUES (src.START_TIME, src.END_TIME, src.USERNAME, src.CREDITS, src.REQUEST_COUNT);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_ANALYST_USAGE'', rows_affected);

    -- 3. CORTEX_DOCUMENT_PROCESSING_USAGE (incremental by QUERY_ID)
    MERGE INTO CORTEX_DOCUMENT_PROCESSING_USAGE tgt
    USING (
        SELECT QUERY_ID, CREDITS_USED, START_TIME, END_TIME, FUNCTION_NAME, MODEL_NAME, OPERATION_NAME, PAGE_COUNT, DOCUMENT_COUNT, FEATURE_COUNT
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_DOCUMENT_PROCESSING_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.QUERY_ID = src.QUERY_ID
    WHEN NOT MATCHED THEN INSERT (QUERY_ID, CREDITS_USED, START_TIME, END_TIME, FUNCTION_NAME, MODEL_NAME, OPERATION_NAME, PAGE_COUNT, DOCUMENT_COUNT, FEATURE_COUNT)
        VALUES (src.QUERY_ID, src.CREDITS_USED, src.START_TIME, src.END_TIME, src.FUNCTION_NAME, src.MODEL_NAME, src.OPERATION_NAME, src.PAGE_COUNT, src.DOCUMENT_COUNT, src.FEATURE_COUNT);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_DOCUMENT_PROCESSING_USAGE'', rows_affected);

    -- 4. CORTEX_FINE_TUNING_USAGE (incremental by START_TIME, MODEL_NAME)
    MERGE INTO CORTEX_FINE_TUNING_USAGE tgt
    USING (
        SELECT START_TIME, END_TIME, MODEL_NAME, TOKEN_CREDITS, TOKENS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FINE_TUNING_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.START_TIME = src.START_TIME AND COALESCE(tgt.MODEL_NAME, '''') = COALESCE(src.MODEL_NAME, '''')
    WHEN MATCHED THEN UPDATE SET tgt.END_TIME = src.END_TIME, tgt.TOKEN_CREDITS = src.TOKEN_CREDITS, tgt.TOKENS = src.TOKENS, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, MODEL_NAME, TOKEN_CREDITS, TOKENS)
        VALUES (src.START_TIME, src.END_TIME, src.MODEL_NAME, src.TOKEN_CREDITS, src.TOKENS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_FINE_TUNING_USAGE'', rows_affected);

    -- 5. CORTEX_FUNCTIONS_QUERY_USAGE (incremental by QUERY_ID)
    MERGE INTO CORTEX_FUNCTIONS_QUERY_USAGE tgt
    USING (
        SELECT f.QUERY_ID, f.WAREHOUSE_ID, f.MODEL_NAME, f.FUNCTION_NAME, f.TOKENS, f.TOKEN_CREDITS, q.START_TIME
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY f
        JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q ON f.QUERY_ID = q.QUERY_ID
        WHERE q.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.QUERY_ID = src.QUERY_ID
    WHEN NOT MATCHED THEN INSERT (QUERY_ID, WAREHOUSE_ID, MODEL_NAME, FUNCTION_NAME, TOKENS, TOKEN_CREDITS, START_TIME)
        VALUES (src.QUERY_ID, src.WAREHOUSE_ID, src.MODEL_NAME, src.FUNCTION_NAME, src.TOKENS, src.TOKEN_CREDITS, src.START_TIME);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_FUNCTIONS_QUERY_USAGE'', rows_affected);

    -- 7. CORTEX_PROVISIONED_THROUGHPUT_USAGE (incremental by PROVISIONED_THROUGHPUT_ID, INTERVAL_START_TIME)
    MERGE INTO CORTEX_PROVISIONED_THROUGHPUT_USAGE tgt
    USING (
        SELECT PROVISIONED_THROUGHPUT_ID, AI_SERVICE, INTERVAL_START_TIME, INTERVAL_END_TIME, CLOUD_SERVICE_PROVIDER, MODEL_NAME, TERM_START_DATE, TERM_END_DATE, PTU_COUNT, PTU_CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_PROVISIONED_THROUGHPUT_USAGE_HISTORY
        WHERE INTERVAL_START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.PROVISIONED_THROUGHPUT_ID = src.PROVISIONED_THROUGHPUT_ID AND tgt.INTERVAL_START_TIME = src.INTERVAL_START_TIME
    WHEN MATCHED THEN UPDATE SET tgt.PTU_CREDITS = src.PTU_CREDITS, tgt.PTU_COUNT = src.PTU_COUNT, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (PROVISIONED_THROUGHPUT_ID, AI_SERVICE, INTERVAL_START_TIME, INTERVAL_END_TIME, CLOUD_SERVICE_PROVIDER, MODEL_NAME, TERM_START_DATE, TERM_END_DATE, PTU_COUNT, PTU_CREDITS)
        VALUES (src.PROVISIONED_THROUGHPUT_ID, src.AI_SERVICE, src.INTERVAL_START_TIME, src.INTERVAL_END_TIME, src.CLOUD_SERVICE_PROVIDER, src.MODEL_NAME, src.TERM_START_DATE, src.TERM_END_DATE, src.PTU_COUNT, src.PTU_CREDITS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_PROVISIONED_THROUGHPUT_USAGE'', rows_affected);

    -- 8. CORTEX_REST_API_USAGE (incremental by REQUEST_ID)
    MERGE INTO CORTEX_REST_API_USAGE tgt
    USING (
        SELECT START_TIME, END_TIME, REQUEST_ID, MODEL_NAME, TOKENS, TOKENS_GRANULAR:input::NUMBER AS INPUT_TOKENS, TOKENS_GRANULAR:output::NUMBER AS OUTPUT_TOKENS, USER_ID, INFERENCE_REGION
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.REQUEST_ID = src.REQUEST_ID
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, REQUEST_ID, MODEL_NAME, TOKENS, INPUT_TOKENS, OUTPUT_TOKENS, USER_ID, INFERENCE_REGION)
        VALUES (src.START_TIME, src.END_TIME, src.REQUEST_ID, src.MODEL_NAME, src.TOKENS, src.INPUT_TOKENS, src.OUTPUT_TOKENS, src.USER_ID, src.INFERENCE_REGION);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_REST_API_USAGE'', rows_affected);

    -- 9a. CORTEX_CODE_CLI_USAGE (incremental by REQUEST_ID)
    MERGE INTO CORTEX_CODE_CLI_USAGE tgt
    USING (
        SELECT USER_ID, REQUEST_ID, PARENT_REQUEST_ID, USAGE_TIME, TOKEN_CREDITS, TOKENS,
               COALESCE(GET(OBJECT_KEYS(TOKENS_GRANULAR), 0)::VARCHAR, ''unknown'') AS MODEL_NAME,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''input''), 0)::NUMBER AS INPUT_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''output''), 0)::NUMBER AS OUTPUT_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''cache_read_input''), 0)::NUMBER AS CACHE_READ_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''cache_write_input''), 0)::NUMBER AS CACHE_WRITE_TOKENS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
        WHERE USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.REQUEST_ID = src.REQUEST_ID
    WHEN MATCHED THEN UPDATE SET tgt.TOKEN_CREDITS = src.TOKEN_CREDITS, tgt.TOKENS = src.TOKENS, tgt.MODEL_NAME = src.MODEL_NAME, tgt.INPUT_TOKENS = src.INPUT_TOKENS, tgt.OUTPUT_TOKENS = src.OUTPUT_TOKENS, tgt.CACHE_READ_TOKENS = src.CACHE_READ_TOKENS, tgt.CACHE_WRITE_TOKENS = src.CACHE_WRITE_TOKENS, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (USER_ID, REQUEST_ID, PARENT_REQUEST_ID, USAGE_TIME, TOKEN_CREDITS, TOKENS, MODEL_NAME, INPUT_TOKENS, OUTPUT_TOKENS, CACHE_READ_TOKENS, CACHE_WRITE_TOKENS)
        VALUES (src.USER_ID, src.REQUEST_ID, src.PARENT_REQUEST_ID, src.USAGE_TIME, src.TOKEN_CREDITS, src.TOKENS, src.MODEL_NAME, src.INPUT_TOKENS, src.OUTPUT_TOKENS, src.CACHE_READ_TOKENS, src.CACHE_WRITE_TOKENS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_CODE_CLI_USAGE'', rows_affected);

    -- 9a2. CORTEX_CODE_SNOWSIGHT_USAGE (incremental by REQUEST_ID)
    MERGE INTO CORTEX_CODE_SNOWSIGHT_USAGE tgt
    USING (
        SELECT USER_ID, REQUEST_ID, PARENT_REQUEST_ID, USAGE_TIME, TOKEN_CREDITS, TOKENS,
               COALESCE(GET(OBJECT_KEYS(TOKENS_GRANULAR), 0)::VARCHAR, ''unknown'') AS MODEL_NAME,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''input''), 0)::NUMBER AS INPUT_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''output''), 0)::NUMBER AS OUTPUT_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''cache_read_input''), 0)::NUMBER AS CACHE_READ_TOKENS,
               COALESCE(GET(GET(TOKENS_GRANULAR, OBJECT_KEYS(TOKENS_GRANULAR)[0]::VARCHAR), ''cache_write_input''), 0)::NUMBER AS CACHE_WRITE_TOKENS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
        WHERE USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.REQUEST_ID = src.REQUEST_ID
    WHEN MATCHED THEN UPDATE SET tgt.TOKEN_CREDITS = src.TOKEN_CREDITS, tgt.TOKENS = src.TOKENS, tgt.MODEL_NAME = src.MODEL_NAME, tgt.INPUT_TOKENS = src.INPUT_TOKENS, tgt.OUTPUT_TOKENS = src.OUTPUT_TOKENS, tgt.CACHE_READ_TOKENS = src.CACHE_READ_TOKENS, tgt.CACHE_WRITE_TOKENS = src.CACHE_WRITE_TOKENS, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (USER_ID, REQUEST_ID, PARENT_REQUEST_ID, USAGE_TIME, TOKEN_CREDITS, TOKENS, MODEL_NAME, INPUT_TOKENS, OUTPUT_TOKENS, CACHE_READ_TOKENS, CACHE_WRITE_TOKENS)
        VALUES (src.USER_ID, src.REQUEST_ID, src.PARENT_REQUEST_ID, src.USAGE_TIME, src.TOKEN_CREDITS, src.TOKENS, src.MODEL_NAME, src.INPUT_TOKENS, src.OUTPUT_TOKENS, src.CACHE_READ_TOKENS, src.CACHE_WRITE_TOKENS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_CODE_SNOWSIGHT_USAGE'', rows_affected);

    -- 9b. CORTEX_AGENT_USAGE (incremental by REQUEST_ID)
    MERGE INTO CORTEX_AGENT_USAGE tgt
    USING (
        SELECT a.START_TIME, a.END_TIME, a.USER_ID, a.USER_NAME,
               UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, a.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
               a.REQUEST_ID, a.PARENT_REQUEST_ID, a.AGENT_DATABASE_NAME, a.AGENT_SCHEMA_NAME, a.AGENT_NAME, a.TOKEN_CREDITS, a.TOKENS,
               COALESCE(GET(OBJECT_KEYS(GET(GET(a.CREDITS_GRANULAR[0], OBJECT_KEYS(a.CREDITS_GRANULAR[0])[0]::VARCHAR), ''cortex_agents'')), 0)::VARCHAR, ''unknown'') AS MODEL_NAME
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY a
        LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON a.USER_ID = u.USER_ID
        WHERE a.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.REQUEST_ID = src.REQUEST_ID
    WHEN MATCHED THEN UPDATE SET tgt.TOKEN_CREDITS = src.TOKEN_CREDITS, tgt.TOKENS = src.TOKENS, tgt.FULL_NAME = src.FULL_NAME, tgt.MODEL_NAME = src.MODEL_NAME, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, USER_ID, USER_NAME, FULL_NAME, REQUEST_ID, PARENT_REQUEST_ID, AGENT_DATABASE_NAME, AGENT_SCHEMA_NAME, AGENT_NAME, TOKEN_CREDITS, TOKENS, MODEL_NAME)
        VALUES (src.START_TIME, src.END_TIME, src.USER_ID, src.USER_NAME, src.FULL_NAME, src.REQUEST_ID, src.PARENT_REQUEST_ID, src.AGENT_DATABASE_NAME, src.AGENT_SCHEMA_NAME, src.AGENT_NAME, src.TOKEN_CREDITS, src.TOKENS, src.MODEL_NAME);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_AGENT_USAGE'', rows_affected);

    -- Cortex Agent: AI Services tiered rate with discount
    UPDATE CORTEX_AGENT_USAGE tgt
    SET COST_USD = COALESCE(tgt.TOKEN_CREDITS, 0) * br.BASE_RATE_PER_CREDIT * (1 - br.TIER_DISCOUNT_PCT / 100)
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''AI_SERVICES''
      AND br.REGION_TYPE = :region_type
      AND DATE(tgt.START_TIME) BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- 9c. SNOWFLAKE_INTELLIGENCE_USAGE (incremental by REQUEST_ID)
    MERGE INTO SNOWFLAKE_INTELLIGENCE_USAGE tgt
    USING (
        SELECT si.START_TIME, si.END_TIME, si.USER_ID, si.USER_NAME,
               UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, si.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
               si.REQUEST_ID, si.PARENT_REQUEST_ID, si.SNOWFLAKE_INTELLIGENCE_NAME, si.AGENT_DATABASE_NAME, si.AGENT_SCHEMA_NAME, si.AGENT_NAME, si.TOKEN_CREDITS, si.TOKENS,
               COALESCE(GET(OBJECT_KEYS(GET(GET(si.CREDITS_GRANULAR[0], OBJECT_KEYS(si.CREDITS_GRANULAR[0])[0]::VARCHAR), ''cortex_agents'')), 0)::VARCHAR, ''unknown'') AS MODEL_NAME
        FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY si
        LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON si.USER_ID = u.USER_ID
        WHERE si.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.REQUEST_ID = src.REQUEST_ID
    WHEN MATCHED THEN UPDATE SET tgt.TOKEN_CREDITS = src.TOKEN_CREDITS, tgt.TOKENS = src.TOKENS, tgt.FULL_NAME = src.FULL_NAME, tgt.MODEL_NAME = src.MODEL_NAME, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, USER_ID, USER_NAME, FULL_NAME, REQUEST_ID, PARENT_REQUEST_ID, SNOWFLAKE_INTELLIGENCE_NAME, AGENT_DATABASE_NAME, AGENT_SCHEMA_NAME, AGENT_NAME, TOKEN_CREDITS, TOKENS, MODEL_NAME)
        VALUES (src.START_TIME, src.END_TIME, src.USER_ID, src.USER_NAME, src.FULL_NAME, src.REQUEST_ID, src.PARENT_REQUEST_ID, src.SNOWFLAKE_INTELLIGENCE_NAME, src.AGENT_DATABASE_NAME, src.AGENT_SCHEMA_NAME, src.AGENT_NAME, src.TOKEN_CREDITS, src.TOKENS, src.MODEL_NAME);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''SNOWFLAKE_INTELLIGENCE_USAGE'', rows_affected);

    -- Snowflake Intelligence: AI Services tiered rate with discount
    UPDATE SNOWFLAKE_INTELLIGENCE_USAGE tgt
    SET COST_USD = COALESCE(tgt.TOKEN_CREDITS, 0) * br.BASE_RATE_PER_CREDIT * (1 - br.TIER_DISCOUNT_PCT / 100)
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''AI_SERVICES''
      AND br.REGION_TYPE = :region_type
      AND DATE(tgt.START_TIME) BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- 9d. CORTEX_SEARCH_DAILY_USAGE (incremental by USAGE_DATE, SERVICE_ID, CONSUMPTION_TYPE)
    MERGE INTO CORTEX_SEARCH_DAILY_USAGE tgt
    USING (
        SELECT USAGE_DATE, DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, SERVICE_ID, CONSUMPTION_TYPE, CREDITS, MODEL_NAME, TOKENS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY
        WHERE USAGE_DATE >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.USAGE_DATE = src.USAGE_DATE AND tgt.SERVICE_ID = src.SERVICE_ID AND tgt.CONSUMPTION_TYPE = src.CONSUMPTION_TYPE
    WHEN MATCHED THEN UPDATE SET tgt.CREDITS = src.CREDITS, tgt.TOKENS = src.TOKENS, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (USAGE_DATE, DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, SERVICE_ID, CONSUMPTION_TYPE, CREDITS, MODEL_NAME, TOKENS)
        VALUES (src.USAGE_DATE, src.DATABASE_NAME, src.SCHEMA_NAME, src.SERVICE_NAME, src.SERVICE_ID, src.CONSUMPTION_TYPE, src.CREDITS, src.MODEL_NAME, src.TOKENS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_SEARCH_DAILY_USAGE'', rows_affected);

    -- 10. CORTEX_SEARCH_SERVING_USAGE (incremental by START_TIME, SERVICE_ID)
    MERGE INTO CORTEX_SEARCH_SERVING_USAGE tgt
    USING (
        SELECT START_TIME, END_TIME, DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, SERVICE_ID, CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_SERVING_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.START_TIME = src.START_TIME AND tgt.SERVICE_ID = src.SERVICE_ID
    WHEN MATCHED THEN UPDATE SET tgt.CREDITS = src.CREDITS, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, DATABASE_NAME, SCHEMA_NAME, SERVICE_NAME, SERVICE_ID, CREDITS)
        VALUES (src.START_TIME, src.END_TIME, src.DATABASE_NAME, src.SCHEMA_NAME, src.SERVICE_NAME, src.SERVICE_ID, src.CREDITS);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_SEARCH_SERVING_USAGE'', rows_affected);

    -- 11. DOCUMENT_AI_USAGE (incremental by QUERY_ID)
    MERGE INTO DOCUMENT_AI_USAGE tgt
    USING (
        SELECT START_TIME, END_TIME, CREDITS_USED, QUERY_ID, OPERATION_NAME, PAGE_COUNT, DOCUMENT_COUNT, FEATURE_COUNT
        FROM SNOWFLAKE.ACCOUNT_USAGE.DOCUMENT_AI_USAGE_HISTORY
        WHERE START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_TIMESTAMP())
    ) src ON tgt.QUERY_ID = src.QUERY_ID
    WHEN NOT MATCHED THEN INSERT (START_TIME, END_TIME, CREDITS_USED, QUERY_ID, OPERATION_NAME, PAGE_COUNT, DOCUMENT_COUNT, FEATURE_COUNT)
        VALUES (src.START_TIME, src.END_TIME, src.CREDITS_USED, src.QUERY_ID, src.OPERATION_NAME, src.PAGE_COUNT, src.DOCUMENT_COUNT, src.FEATURE_COUNT);
    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''DOCUMENT_AI_USAGE'', rows_affected);

    -- Rebuild unified summary table (MERGE for incremental updates)
    MERGE INTO CORTEX_AI_UNIFIED_COSTS tgt
    USING (
        SELECT DATE(USAGE_TIME) AS USAGE_DATE, ''LLM Functions'' AS SERVICE_CATEGORY, ''CORTEX_AISQL'' AS SERVICE_NAME, MODEL_NAME, SUM(TOKEN_CREDITS) AS CREDITS, SUM(TOKENS) AS TOKENS, NULL::NUMBER AS INPUT_TOKENS, NULL::NUMBER AS OUTPUT_TOKENS, NULL::NUMBER AS CACHE_READ_TOKENS, NULL::NUMBER AS CACHE_WRITE_TOKENS, COUNT(*) AS REQUEST_COUNT
        FROM CORTEX_AISQL_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''Analyst'', ''CORTEX_ANALYST'', ''N/A'', SUM(CREDITS), NULL, NULL, NULL, NULL, NULL, SUM(REQUEST_COUNT)
        FROM CORTEX_ANALYST_USAGE GROUP BY 1
        UNION ALL
        SELECT DATE(START_TIME), ''Document Processing'', ''CORTEX_DOCUMENT_PROCESSING'', COALESCE(MODEL_NAME, ''N/A''), SUM(CREDITS_USED), NULL, NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_DOCUMENT_PROCESSING_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''Fine Tuning'', ''CORTEX_FINE_TUNING'', COALESCE(MODEL_NAME, ''N/A''), SUM(TOKEN_CREDITS), SUM(TOKENS), NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_FINE_TUNING_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(INTERVAL_START_TIME), ''Provisioned Throughput'', ''CORTEX_PROVISIONED_THROUGHPUT'', COALESCE(MODEL_NAME, ''N/A''), SUM(PTU_CREDITS), NULL, NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_PROVISIONED_THROUGHPUT_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''REST API'', ''CORTEX_REST_API'', COALESCE(MODEL_NAME, ''N/A''), NULL, SUM(TOKENS), SUM(INPUT_TOKENS), SUM(OUTPUT_TOKENS), NULL, NULL, COUNT(*)
        FROM CORTEX_REST_API_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(USAGE_DATE), ''Search'', ''CORTEX_SEARCH'', COALESCE(MODEL_NAME, ''N/A''), SUM(CREDITS), SUM(TOKENS), NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_SEARCH_DAILY_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''Search'', ''CORTEX_SEARCH_SERVING'', ''N/A'', SUM(CREDITS), NULL, NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_SEARCH_SERVING_USAGE GROUP BY 1
        UNION ALL
        SELECT DATE(START_TIME), ''Document AI'', ''DOCUMENT_AI'', ''N/A'', SUM(CREDITS_USED), NULL, NULL, NULL, NULL, NULL, COUNT(*)
        FROM DOCUMENT_AI_USAGE GROUP BY 1
        UNION ALL
        SELECT DATE(START_TIME), ''LLM Functions Query'', ''CORTEX_FUNCTIONS_QUERY'', COALESCE(MODEL_NAME, ''N/A''), SUM(TOKEN_CREDITS), SUM(TOKENS), NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_FUNCTIONS_QUERY_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(USAGE_TIME), ''Cortex Code CLI'', ''CORTEX_CODE_CLI'', COALESCE(MODEL_NAME, ''N/A''), SUM(TOKEN_CREDITS), SUM(TOKENS), SUM(INPUT_TOKENS), SUM(OUTPUT_TOKENS), SUM(CACHE_READ_TOKENS), SUM(CACHE_WRITE_TOKENS), COUNT(*)
        FROM CORTEX_CODE_CLI_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(USAGE_TIME), ''Cortex Code Snowsight'', ''CORTEX_CODE_SNOWSIGHT'', COALESCE(MODEL_NAME, ''N/A''), SUM(TOKEN_CREDITS), SUM(TOKENS), SUM(INPUT_TOKENS), SUM(OUTPUT_TOKENS), SUM(CACHE_READ_TOKENS), SUM(CACHE_WRITE_TOKENS), COUNT(*)
        FROM CORTEX_CODE_SNOWSIGHT_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''Cortex Agent'', ''CORTEX_AGENT'', COALESCE(MODEL_NAME, ''unknown''), SUM(TOKEN_CREDITS), SUM(TOKENS), NULL, NULL, NULL, NULL, COUNT(*)
        FROM CORTEX_AGENT_USAGE GROUP BY 1, 4
        UNION ALL
        SELECT DATE(START_TIME), ''Snowflake Intelligence'', ''SNOWFLAKE_INTELLIGENCE'', COALESCE(MODEL_NAME, ''unknown''), SUM(TOKEN_CREDITS), SUM(TOKENS), NULL, NULL, NULL, NULL, COUNT(*)
        FROM SNOWFLAKE_INTELLIGENCE_USAGE GROUP BY 1, 4
    ) src ON tgt.USAGE_DATE = src.USAGE_DATE AND tgt.SERVICE_CATEGORY = src.SERVICE_CATEGORY 
             AND tgt.SERVICE_NAME = src.SERVICE_NAME AND COALESCE(tgt.MODEL_NAME, ''N/A'') = COALESCE(src.MODEL_NAME, ''N/A'')
    WHEN MATCHED THEN UPDATE SET tgt.CREDITS = src.CREDITS, tgt.TOKENS = src.TOKENS, tgt.INPUT_TOKENS = src.INPUT_TOKENS, tgt.OUTPUT_TOKENS = src.OUTPUT_TOKENS, tgt.CACHE_READ_TOKENS = src.CACHE_READ_TOKENS, tgt.CACHE_WRITE_TOKENS = src.CACHE_WRITE_TOKENS, tgt.REQUEST_COUNT = src.REQUEST_COUNT, tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (USAGE_DATE, SERVICE_CATEGORY, SERVICE_NAME, MODEL_NAME, CREDITS, TOKENS, INPUT_TOKENS, OUTPUT_TOKENS, CACHE_READ_TOKENS, CACHE_WRITE_TOKENS, REQUEST_COUNT)
        VALUES (src.USAGE_DATE, src.SERVICE_CATEGORY, src.SERVICE_NAME, src.MODEL_NAME, src.CREDITS, src.TOKENS, src.INPUT_TOKENS, src.OUTPUT_TOKENS, src.CACHE_READ_TOKENS, src.CACHE_WRITE_TOKENS, src.REQUEST_COUNT);

    rows_affected := SQLROWCOUNT;
    result := OBJECT_INSERT(result, ''CORTEX_AI_UNIFIED_COSTS'', rows_affected);

    -- Apply dynamic credit rates to unified costs based on service type
    -- AI Services (CoCo, Agent, SI): tiered rate with discount, region-dependent
    UPDATE CORTEX_AI_UNIFIED_COSTS tgt
    SET COST_USD = COALESCE(tgt.CREDITS, 0) * br.BASE_RATE_PER_CREDIT * (1 - br.TIER_DISCOUNT_PCT / 100)
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''AI_SERVICES''
      AND br.REGION_TYPE = :region_type
      AND tgt.SERVICE_NAME IN (''CORTEX_CODE_CLI'', ''CORTEX_CODE_SNOWSIGHT'', ''CORTEX_AGENT'', ''SNOWFLAKE_INTELLIGENCE'')
      AND tgt.USAGE_DATE BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- All other credit-based services: standard rate (no region classification)
    UPDATE CORTEX_AI_UNIFIED_COSTS tgt
    SET COST_USD = COALESCE(tgt.CREDITS, 0) * br.BASE_RATE_PER_CREDIT
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''STANDARD''
      AND br.REGION_TYPE = ''ANY''
      AND tgt.SERVICE_NAME NOT IN (''CORTEX_REST_API'', ''CORTEX_CODE_CLI'', ''CORTEX_CODE_SNOWSIGHT'', ''CORTEX_AGENT'', ''SNOWFLAKE_INTELLIGENCE'')
      AND tgt.USAGE_DATE BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- REST API: token-based pricing (unchanged)
    UPDATE CORTEX_AI_UNIFIED_COSTS tgt
    SET COST_USD = (COALESCE(tgt.INPUT_TOKENS, 0) * COALESCE(tr.INPUT_RATE_PER_1M, 0) / 1000000.0
                  + COALESCE(tgt.OUTPUT_TOKENS, 0) * COALESCE(tr.OUTPUT_RATE_PER_1M, 0) / 1000000.0)
                  * (1 - COALESCE(tr.DISCOUNT_PCT, 0) / 100.0)
    FROM REST_API_TOKEN_RATES tr
    WHERE tgt.MODEL_NAME = tr.MODEL_NAME
      AND tgt.SERVICE_NAME = ''CORTEX_REST_API''
      AND tgt.USAGE_DATE >= tr.EFFECTIVE_START_DATE
      AND tgt.USAGE_DATE <= tr.EFFECTIVE_END_DATE;

    result := OBJECT_INSERT(result, ''REGION_TYPE'', region_type);
    result := OBJECT_INSERT(result, ''REFRESH_COMPLETED_AT'', CURRENT_TIMESTAMP()::VARCHAR);
    result := OBJECT_INSERT(result, ''DAYS_BACK'', :DAYS_BACK);

    RETURN result;
END;
';

 
CREATE OR REPLACE PROCEDURE REFRESH_USER_AI_COSTS(DAYS_BACK INT DEFAULT 7)
RETURNS VARCHAR
LANGUAGE SQL
AS
'
DECLARE
    rows_affected INT;
    region_type VARCHAR;
    cross_region_value VARCHAR;
BEGIN
    SHOW PARAMETERS LIKE ''CORTEX_ENABLED_CROSS_REGION'' IN ACCOUNT;
    LET rs RESULTSET := (SELECT "value" AS VAL FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
    LET cur CURSOR FOR rs;
    cross_region_value := ''DISABLED'';
    FOR row_var IN cur DO
        cross_region_value := row_var.VAL;
    END FOR;
    IF (cross_region_value IN (''ANY_REGION'', ''AWS_GLOBAL'', ''GCP_GLOBAL'', ''AZURE_GLOBAL'')) THEN
        region_type := ''GLOBAL'';
    ELSE
        region_type := ''REGIONAL'';
    END IF;

    MERGE INTO USER_AI_COSTS tgt
    USING (
        SELECT * FROM (
            SELECT 
                COALESCE(u.NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(MAX(a.USAGE_TIME)) AS USAGE_DATE,
                MAX(a.USAGE_TIME)::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_AISQL'' AS SERVICE_NAME,
                ''LLM Functions'' AS SERVICE_CATEGORY,
                MAX(a.MODEL_NAME) AS MODEL_NAME,
                SUM(a.TOKENS) AS TOKENS,
                NULL::NUMBER AS INPUT_TOKENS,
                NULL::NUMBER AS OUTPUT_TOKENS,
                NULL::NUMBER AS CACHE_READ_TOKENS,
                NULL::NUMBER AS CACHE_WRITE_TOKENS,
                SUM(a.TOKEN_CREDITS) AS CREDITS,
                a.QUERY_ID,
                MAX(q.TOTAL_ELAPSED_TIME) AS DURATION_MS,
                MAX(LEFT(q.QUERY_TEXT, 1000)) AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AISQL_USAGE_HISTORY a
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON a.USER_ID = u.USER_ID
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q ON a.QUERY_ID = q.QUERY_ID
            WHERE a.USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
              AND a.QUERY_ID IS NOT NULL
            GROUP BY a.QUERY_ID, u.NAME, u.FIRST_NAME, u.LAST_NAME
            
            UNION ALL
            
            SELECT 
                COALESCE(q.USER_NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), q.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(d.START_TIME) AS USAGE_DATE,
                d.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_DOCUMENT_PROCESSING'' AS SERVICE_NAME,
                ''Document Processing'' AS SERVICE_CATEGORY,
                COALESCE(d.MODEL_NAME, ''N/A'') AS MODEL_NAME,
                NULL AS TOKENS,
                NULL AS INPUT_TOKENS,
                NULL AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                d.CREDITS_USED AS CREDITS,
                d.QUERY_ID,
                q.TOTAL_ELAPSED_TIME AS DURATION_MS,
                LEFT(q.QUERY_TEXT, 1000) AS QUERY_TEXT,
                ROW_NUMBER() OVER (PARTITION BY d.QUERY_ID ORDER BY d.START_TIME DESC) AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_DOCUMENT_PROCESSING_USAGE_HISTORY d
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q ON d.QUERY_ID = q.QUERY_ID
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON q.USER_NAME = u.NAME
            WHERE d.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
              AND d.QUERY_ID IS NOT NULL
            
            UNION ALL
            
            SELECT 
                COALESCE(ca.USERNAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), ca.USERNAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(ca.START_TIME) AS USAGE_DATE,
                ca.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_ANALYST'' AS SERVICE_NAME,
                ''Analyst'' AS SERVICE_CATEGORY,
                ''N/A'' AS MODEL_NAME,
                NULL AS TOKENS,
                NULL AS INPUT_TOKENS,
                NULL AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                ca.CREDITS,
                TO_VARCHAR(ca.START_TIME, ''YYYYMMDDHH24MISSFF6'') || ''_'' || COALESCE(ca.USERNAME, ''SYSTEM'') || ''_'' || ROW_NUMBER() OVER (PARTITION BY ca.START_TIME, ca.USERNAME ORDER BY ca.END_TIME) AS QUERY_ID,
                NULL AS DURATION_MS,
                ''Cortex Analyst: '' || ca.REQUEST_COUNT || '' requests'' AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY ca
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON ca.USERNAME = u.LOGIN_NAME
            WHERE ca.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
            
            UNION ALL
            
            SELECT 
                COALESCE(u.NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(r.START_TIME) AS USAGE_DATE,
                r.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_REST_API'' AS SERVICE_NAME,
                ''REST API'' AS SERVICE_CATEGORY,
                COALESCE(r.MODEL_NAME, ''N/A'') AS MODEL_NAME,
                r.TOKENS,
                r.TOKENS_GRANULAR:input::NUMBER AS INPUT_TOKENS,
                r.TOKENS_GRANULAR:output::NUMBER AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                NULL AS CREDITS,
                r.REQUEST_ID AS QUERY_ID,
                NULL AS DURATION_MS,
                ''REST API: '' || COALESCE(r.INFERENCE_REGION, ''N/A'') AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY r
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON r.USER_ID = u.USER_ID
            WHERE r.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
            
            UNION ALL
            
            SELECT 
                COALESCE(q.USER_NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), q.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(q.START_TIME) AS USAGE_DATE,
                q.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_FUNCTIONS_QUERY'' AS SERVICE_NAME,
                ''LLM Functions Query'' AS SERVICE_CATEGORY,
                COALESCE(f.MODEL_NAME, ''N/A'') AS MODEL_NAME,
                f.TOKENS,
                NULL AS INPUT_TOKENS,
                NULL AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                f.TOKEN_CREDITS AS CREDITS,
                f.QUERY_ID,
                q.TOTAL_ELAPSED_TIME AS DURATION_MS,
                LEFT(q.QUERY_TEXT, 1000) AS QUERY_TEXT,
                ROW_NUMBER() OVER (PARTITION BY f.QUERY_ID ORDER BY q.START_TIME DESC) AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY f
            JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q ON f.QUERY_ID = q.QUERY_ID
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON q.USER_NAME = u.NAME
            WHERE q.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
              AND f.QUERY_ID IS NOT NULL
            
            UNION ALL
            
            SELECT 
                COALESCE(u.NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(c.USAGE_TIME) AS USAGE_DATE,
                c.USAGE_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_CODE_CLI'' AS SERVICE_NAME,
                ''Cortex Code CLI'' AS SERVICE_CATEGORY,
                COALESCE(GET(OBJECT_KEYS(c.TOKENS_GRANULAR), 0)::VARCHAR, ''unknown'') AS MODEL_NAME,
                c.TOKENS,
                COALESCE(GET(GET(c.TOKENS_GRANULAR, OBJECT_KEYS(c.TOKENS_GRANULAR)[0]::VARCHAR), ''input''), 0)::NUMBER AS INPUT_TOKENS,
                COALESCE(GET(GET(c.TOKENS_GRANULAR, OBJECT_KEYS(c.TOKENS_GRANULAR)[0]::VARCHAR), ''output''), 0)::NUMBER AS OUTPUT_TOKENS,
                COALESCE(GET(GET(c.TOKENS_GRANULAR, OBJECT_KEYS(c.TOKENS_GRANULAR)[0]::VARCHAR), ''cache_read_input''), 0)::NUMBER AS CACHE_READ_TOKENS,
                COALESCE(GET(GET(c.TOKENS_GRANULAR, OBJECT_KEYS(c.TOKENS_GRANULAR)[0]::VARCHAR), ''cache_write_input''), 0)::NUMBER AS CACHE_WRITE_TOKENS,
                c.TOKEN_CREDITS AS CREDITS,
                c.REQUEST_ID AS QUERY_ID,
                NULL AS DURATION_MS,
                ''Cortex Code CLI'' AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY c
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON c.USER_ID = u.USER_ID
            WHERE c.USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())

            UNION ALL

            SELECT 
                COALESCE(u.NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), u.NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(cs.USAGE_TIME) AS USAGE_DATE,
                cs.USAGE_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_CODE_SNOWSIGHT'' AS SERVICE_NAME,
                ''Cortex Code Snowsight'' AS SERVICE_CATEGORY,
                COALESCE(GET(OBJECT_KEYS(cs.TOKENS_GRANULAR), 0)::VARCHAR, ''unknown'') AS MODEL_NAME,
                cs.TOKENS,
                COALESCE(GET(GET(cs.TOKENS_GRANULAR, OBJECT_KEYS(cs.TOKENS_GRANULAR)[0]::VARCHAR), ''input''), 0)::NUMBER AS INPUT_TOKENS,
                COALESCE(GET(GET(cs.TOKENS_GRANULAR, OBJECT_KEYS(cs.TOKENS_GRANULAR)[0]::VARCHAR), ''output''), 0)::NUMBER AS OUTPUT_TOKENS,
                COALESCE(GET(GET(cs.TOKENS_GRANULAR, OBJECT_KEYS(cs.TOKENS_GRANULAR)[0]::VARCHAR), ''cache_read_input''), 0)::NUMBER AS CACHE_READ_TOKENS,
                COALESCE(GET(GET(cs.TOKENS_GRANULAR, OBJECT_KEYS(cs.TOKENS_GRANULAR)[0]::VARCHAR), ''cache_write_input''), 0)::NUMBER AS CACHE_WRITE_TOKENS,
                cs.TOKEN_CREDITS AS CREDITS,
                cs.REQUEST_ID AS QUERY_ID,
                NULL AS DURATION_MS,
                ''Cortex Code Snowsight'' AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY cs
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON cs.USER_ID = u.USER_ID
            WHERE cs.USAGE_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())

            UNION ALL

            SELECT 
                COALESCE(a.USER_NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), a.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(a.START_TIME) AS USAGE_DATE,
                a.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''CORTEX_AGENT'' AS SERVICE_NAME,
                ''Cortex Agent'' AS SERVICE_CATEGORY,
                COALESCE(a.AGENT_DATABASE_NAME || ''.'' || a.AGENT_SCHEMA_NAME || ''.'' || a.AGENT_NAME, ''N/A'') AS MODEL_NAME,
                a.TOKENS,
                NULL AS INPUT_TOKENS,
                NULL AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                a.TOKEN_CREDITS AS CREDITS,
                a.REQUEST_ID AS QUERY_ID,
                NULL AS DURATION_MS,
                ''Cortex Agent: '' || COALESCE(a.AGENT_NAME, ''unnamed'') AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY a
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON a.USER_ID = u.user_id
            WHERE a.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())

            UNION ALL

            SELECT 
                COALESCE(si.USER_NAME, ''SYSTEM'') AS USER_NAME,
                UPPER(COALESCE(NULLIF(TRIM(u.FIRST_NAME || '' '' || u.LAST_NAME), ''''), si.USER_NAME, ''SYSTEM'')) AS FULL_NAME,
                DATE(si.START_TIME) AS USAGE_DATE,
                si.START_TIME::TIMESTAMP_TZ AS USAGE_TIME,
                ''SNOWFLAKE_INTELLIGENCE'' AS SERVICE_NAME,
                ''Snowflake Intelligence'' AS SERVICE_CATEGORY,
                COALESCE(si.AGENT_DATABASE_NAME || ''.'' || si.AGENT_SCHEMA_NAME || ''.'' || si.AGENT_NAME, ''N/A'') AS MODEL_NAME,
                si.TOKENS,
                NULL AS INPUT_TOKENS,
                NULL AS OUTPUT_TOKENS,
                NULL AS CACHE_READ_TOKENS,
                NULL AS CACHE_WRITE_TOKENS,
                si.TOKEN_CREDITS AS CREDITS,
                si.REQUEST_ID AS QUERY_ID,
                NULL AS DURATION_MS,
                ''Snowflake Intelligence: '' || COALESCE(si.AGENT_NAME, ''unnamed'') AS QUERY_TEXT,
                1 AS rn
            FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY si
            LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS u ON si.USER_ID = u.USER_ID
            WHERE si.START_TIME >= DATEADD(''day'', -:DAYS_BACK, CURRENT_DATE())
        ) WHERE rn = 1
    ) src 
    ON tgt.QUERY_ID = src.QUERY_ID AND tgt.SERVICE_NAME = src.SERVICE_NAME
    WHEN MATCHED THEN UPDATE SET 
        tgt.SERVICE_CATEGORY = src.SERVICE_CATEGORY,
        tgt.CREDITS = src.CREDITS,
        tgt.TOKENS = src.TOKENS,
        tgt.INPUT_TOKENS = src.INPUT_TOKENS,
        tgt.OUTPUT_TOKENS = src.OUTPUT_TOKENS,
        tgt.CACHE_READ_TOKENS = src.CACHE_READ_TOKENS,
        tgt.CACHE_WRITE_TOKENS = src.CACHE_WRITE_TOKENS,
        tgt.LAST_REFRESHED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (USER_NAME, FULL_NAME, USAGE_DATE, USAGE_TIME, SERVICE_CATEGORY, SERVICE_NAME, MODEL_NAME, TOKENS, INPUT_TOKENS, OUTPUT_TOKENS, CACHE_READ_TOKENS, CACHE_WRITE_TOKENS, CREDITS, QUERY_ID, DURATION_MS, QUERY_TEXT)
        VALUES (src.USER_NAME, src.FULL_NAME, src.USAGE_DATE, src.USAGE_TIME, src.SERVICE_CATEGORY, src.SERVICE_NAME, src.MODEL_NAME, src.TOKENS, src.INPUT_TOKENS, src.OUTPUT_TOKENS, src.CACHE_READ_TOKENS, src.CACHE_WRITE_TOKENS, src.CREDITS, src.QUERY_ID, src.DURATION_MS, src.QUERY_TEXT);

    rows_affected := SQLROWCOUNT;

    -- Apply dynamic credit rates based on service type
    -- AI Services (CoCo, Agent, SI): tiered rate with discount, region-dependent
    UPDATE USER_AI_COSTS tgt
    SET COST_USD = COALESCE(tgt.CREDITS, 0) * br.BASE_RATE_PER_CREDIT * (1 - br.TIER_DISCOUNT_PCT / 100)
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''AI_SERVICES''
      AND br.REGION_TYPE = :region_type
      AND tgt.SERVICE_NAME IN (''CORTEX_CODE_CLI'', ''CORTEX_CODE_SNOWSIGHT'', ''CORTEX_AGENT'', ''SNOWFLAKE_INTELLIGENCE'')
      AND tgt.USAGE_DATE BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- All other credit-based services: standard rate (no region classification)
    UPDATE USER_AI_COSTS tgt
    SET COST_USD = COALESCE(tgt.CREDITS, 0) * br.BASE_RATE_PER_CREDIT
    FROM CREDIT_BASE_RATES br
    WHERE br.SERVICE_TIER = ''STANDARD''
      AND br.REGION_TYPE = ''ANY''
      AND tgt.SERVICE_NAME NOT IN (''CORTEX_REST_API'', ''CORTEX_CODE_CLI'', ''CORTEX_CODE_SNOWSIGHT'', ''CORTEX_AGENT'', ''SNOWFLAKE_INTELLIGENCE'')
      AND tgt.USAGE_DATE BETWEEN br.EFFECTIVE_START_DATE AND br.EFFECTIVE_END_DATE;

    -- REST API: token-based pricing (unchanged)
    UPDATE USER_AI_COSTS tgt
    SET COST_USD = (COALESCE(tgt.INPUT_TOKENS, 0) * COALESCE(tr.INPUT_RATE_PER_1M, 0) / 1000000.0
                  + COALESCE(tgt.OUTPUT_TOKENS, 0) * COALESCE(tr.OUTPUT_RATE_PER_1M, 0) / 1000000.0)
                  * (1 - COALESCE(tr.DISCOUNT_PCT, 0) / 100.0)
    FROM REST_API_TOKEN_RATES tr
    WHERE tgt.MODEL_NAME = tr.MODEL_NAME
      AND tgt.SERVICE_NAME = ''CORTEX_REST_API''
      AND tgt.USAGE_DATE >= tr.EFFECTIVE_START_DATE
      AND tgt.USAGE_DATE <= tr.EFFECTIVE_END_DATE;

    RETURN ''Refreshed '' || rows_affected || '' rows (region_type='' || region_type || '')'';
END;
';

 
CALL REFRESH_CORTEX_AI_COSTS(365);
CALL REFRESH_USER_AI_COSTS(365);

 
CREATE OR REPLACE TASK REFRESH_CORTEX_AI_COSTS_DAILY
  WAREHOUSE = {{WAREHOUSE}}
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Daily refresh of Cortex AI cost data - root task'
AS
  CALL REFRESH_CORTEX_AI_COSTS(7);

CREATE OR REPLACE TASK REFRESH_USER_AI_COSTS_DAILY
  WAREHOUSE = {{WAREHOUSE}}
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Daily refresh of user AI cost data - child task'
AS
  CALL REFRESH_USER_AI_COSTS(7);

ALTER TASK REFRESH_USER_AI_COSTS_DAILY RESUME;

ALTER TASK REFRESH_CORTEX_AI_COSTS_DAILY RESUME;


CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE;


