YOUR_PROFILE_NAME:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ROLE
      warehouse: WAREHOUSE
      database: DATABASE
      schema: SCHEMA
      account: ACCOUNT
      user: USERNAME
      threads: 1
