USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.FoodTruck (
    TruckID INT IDENTITY(1,1) ORDER NOT NULL,
    TruckGUID VARCHAR NOT NULL DEFAULT (UUID_STRING()) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__FoodTruck__Truck__3D5E1FD2' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    TruckName NVARCHAR(200) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    LicensePlate VARCHAR(20) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    CityID INT NOT NULL,
    TruckConfig NVARCHAR COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    YearPurchased INT NULL,
    MaxCapacity INT NOT NULL DEFAULT ((500)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__FoodTruck__MaxCa__3E52440B' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    IsOperational BOOLEAN NOT NULL DEFAULT true,
    CreatedAt TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__FoodTruck__Creat__403A8C7D' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/,
    ModifiedAt TIMESTAMP_NTZ(3) NULL
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;