name: snowpark-ml-hol
channels:
  - defaults
dependencies:
  - notebook
  - snowflake-snowpark-python
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pip
  - cachetools
  - python==3.9.18
  - xgboost
  - lightgbm
