name: snowpark-ml-hol
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python
  - pandas
  - xgboost
  - notebook
  - scikit-learn
  - cachetools
  - seaborn
  - matplotlib
  - pip:
    - snowflake-ml-python # temporary till it's in the Snowflake conda channel
