source_platform: SqlServer
target_platform: snowflake
output_directory_path: ./.scai/test/reports
validation_database: TASTYBYTESDB
validation_configuration:
  schema_validation: false
  metrics_validation: true
  row_validation: true
  max_failed_rows_number: 100
  in_memory_row_threshold: 100000
  tolerance: 0.001
  max_cell_diffs: 1000
