/*=============================================================
  HOL_COCO_COWORK - Step 1: Setup
  Creates warehouse, database, schemas, stages, and tables.
  
  Run this in a SQL cell in your Snowflake Workspace.
=============================================================*/

USE ROLE ACCOUNTADMIN;

--------------------------------------------------------------
-- 1. Create Warehouse & Compute Pool
--------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS HOL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE HOL_WH;

CREATE COMPUTE POOL IF NOT EXISTS HOL_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300;

--------------------------------------------------------------
-- 2. Create Database & Schemas
--------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS HOL_COCO_COWORK;

USE DATABASE HOL_COCO_COWORK;

CREATE SCHEMA IF NOT EXISTS DATA;
CREATE SCHEMA IF NOT EXISTS TOOLS;
CREATE SCHEMA IF NOT EXISTS AGENTS;

--------------------------------------------------------------
-- 3. Create File Formats & Stages
--------------------------------------------------------------
USE SCHEMA DATA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE HOL_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  FILE_FORMAT = CSV_FORMAT;

USE SCHEMA TOOLS;

CREATE OR REPLACE STAGE SKILLS_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

USE SCHEMA DATA;

--------------------------------------------------------------
-- 4. Create Tables (UUIDs generated by Snowflake)
--------------------------------------------------------------
CREATE OR REPLACE TABLE DIM_STORE (
    STORE_ID       VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    STORE_NAME     VARCHAR(100)  NOT NULL,
    ADDRESS        VARCHAR(200)  NOT NULL,
    CITY           VARCHAR(100)  NOT NULL,
    STATE          VARCHAR(2)    NOT NULL,
    ZIP_CODE       VARCHAR(10)   NOT NULL,
    LATITUDE       FLOAT,
    LONGITUDE      FLOAT,
    OPENED_DATE    DATE,
    CONSTRAINT PK_DIM_STORE PRIMARY KEY (STORE_ID)
);

CREATE OR REPLACE TABLE DIM_ITEM (
    ITEM_ID        VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    ITEM_NAME      VARCHAR(200)  NOT NULL,
    CATEGORY       VARCHAR(100)  NOT NULL,
    UNIT_PRICE     NUMBER(10,2)  NOT NULL,
    COST_PRICE     NUMBER(10,2)  NOT NULL,
    CALORIES       INTEGER,
    IS_SPICY       BOOLEAN,
    CONSTRAINT PK_DIM_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE OR REPLACE TABLE FACT_ITEM_SALES (
    SALE_ID        VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    STORE_ID       VARCHAR(36)   NOT NULL,
    ITEM_ID        VARCHAR(36)   NOT NULL,
    SALE_DATE      DATE          NOT NULL,
    QUANTITY_SOLD  INTEGER       NOT NULL,
    UNIT_PRICE     NUMBER(10,2)  NOT NULL,
    DISCOUNT_PCT   INTEGER       DEFAULT 0,
    TOTAL_SALES    NUMBER(12,2)  NOT NULL,
    CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALE_ID),
    CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES DIM_STORE(STORE_ID),
    CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES DIM_ITEM(ITEM_ID)
);
