USE DATABASE TastyBytesDB;

CREATE OR REPLACE TABLE TastyBytes.MenuItem (
    MenuItemID INT IDENTITY(1,1) ORDER NOT NULL,
    MenuID INT NOT NULL,
    ItemName NVARCHAR(200) COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NOT NULL,
    ItemDescription NVARCHAR COLLATE 'EN-CI-AS' /*** SSC-PRF-0002 - CASE INSENSITIVE COLUMNS CAN DECREASE THE PERFORMANCE OF QUERIES ***/ /*** SSC-FDM-TS0002 - COLLATION FOR VALUE CP1 NOT SUPPORTED ***/ NULL,
    BasePrice NUMBER(38, 4) NOT NULL,
    CalorieCount INT NULL,
    IsVegetarian BOOLEAN NOT NULL DEFAULT false,
    IsGlutenFree BOOLEAN NOT NULL DEFAULT false,
    IsSpicy BOOLEAN NOT NULL DEFAULT false,
    PriceWithTax DECIMAL(10, 2) NULL,
    RowVer BINARY(8) /*** SSC-FDM-TS0046 - ROWVERSION/TIMESTAMP DATA TYPE AUTO-GENERATES UNIQUE VALUES ON INSERT AND UPDATE IN SQL SERVER. THIS BEHAVIOR IS NOT REPLICATED IN SNOWFLAKE BINARY(8). ***/ NOT NULL,
    CreatedAt TIMESTAMP_NTZ(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP() :: TIMESTAMP_NTZ(3)) /*** SSC-FDM-0012 - CONSTRAINT NAME 'DF__MenuItem__Create__49C3F6B7' IN DEFAULT EXPRESSION CONSTRAINT IS NOT SUPPORTED IN SNOWFLAKE ***/
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
;