export const BRAND_COLORS: Record<string, string> = {
  'NORDWAVE': '#1E40AF',
  'FROSTPEAK': '#0F766E',
  'AVALANCHE PRO': '#DC2626',
  'RIDGELINE': '#65A30D',
  'POWDERHOUND': '#EA580C',
  'GLACIERTECH': '#4F46E5',
  'CARVE NATION': '#334155',
  'WILD DESCENT': '#7C3AED',
  // SNOWFIELD PRO catalog brands (title-case)
  'Ridgeline': '#65A30D',
  'Black Crows': '#1E40AF',
  'Salomon': '#DC2626',
  'Marker': '#EA580C',
  'Volkl': '#4F46E5',
  'Völkl': '#4F46E5',
  'Tecnica': '#0F766E',
  'Dynastar': '#334155',
  'Giro': '#7C3AED',
  'Ortovox': '#0891B2',
  'Hestra': '#B45309',
  'Buff': '#6D28D9',
  'K2': '#0E7490',
  'Dakine': '#9333EA',
  'Dynafit': '#059669',
  'Icebreaker': '#0284C7',
  'Lange': '#D97706',
  'Leki': '#E11D48',
  'Mammut': '#B91C1C',
  'Patagonia': '#7C3AED',
};

export const BRAND_TAGLINES: Record<string, string> = {
  'NORDWAVE':      'Engineered to the millimetre',
  'FROSTPEAK':     'From first run to last light',
  'AVALANCHE PRO': 'Where maps end',
  'RIDGELINE':     'Every gram counts',
  'POWDERHOUND':   'Built to stomp',
  'GLACIERTECH':   'Engineered for absolute zero',
  'CARVE NATION':  'Every millisecond counts',
  'WILD DESCENT':  'Built for the worst day',
  // SNOWFIELD PRO catalog brands
  'Ridgeline':   'Every gram counts',
  'Black Crows': 'Free your line',
  'Salomon':     'Tomorrow is yours',
  'Marker':      'Precision binding technology',
  'Volkl':       'True to skiing',
  'Tecnica':     'The perfect fit',
  'Dynastar':    'Legendary performance',
  'Giro':        'Protection meets style',
  'Ortovox':     'Protects what matters',
  'Hestra':      'Handcrafted since 1936',
  'Buff':        'Do more with less',
};

export const BRAND_IDENTITY: Record<string, string> = {
  'NORDWAVE':      'Scandinavian precision engineering',
  'FROSTPEAK':     'All-mountain versatility',
  'AVALANCHE PRO': 'Big mountain adventure',
  'RIDGELINE':     'Ultralight touring',
  'POWDERHOUND':   'Park & freestyle culture',
  'GLACIERTECH':   'Extreme cold specialists',
  'CARVE NATION':  'Alpine racing purists',
  'WILD DESCENT':  'Storm chasers',
  // SNOWFIELD PRO catalog brands
  'Ridgeline':   'Freeride & touring specialists',
  'Black Crows': 'Big mountain freeride',
  'Salomon':     'All-mountain performance',
  'Marker':      'Binding innovation',
  'Volkl':       'German engineering',
  'Tecnica':     'Boot fitting experts',
  'Dynastar':    'French ski heritage',
  'Giro':        'Helmet & goggle pioneers',
  'Ortovox':     'Mountain safety experts',
  'Hestra':      'Swedish glove craftsmanship',
  'Buff':        'Outdoor accessories',
};

// Keywords that find each brand via Cortex Search
export const BRAND_SEARCH_HINTS: Record<string, string> = {
  'NORDWAVE':      'precision engineered technical competition-grade',
  'FROSTPEAK':     'versatile all-conditions reliable all-mountain',
  'AVALANCHE PRO': 'adventure backcountry off-piste exploration',
  'RIDGELINE':     'ultralight touring packable expedition',
  'POWDERHOUND':   'freestyle park tricks stomp playful',
  'GLACIERTECH':   'ultra-cold sub-zero polar thermal insulation',
  'CARVE NATION':  'racing FIS competition speed gates',
  'WILD DESCENT':  'storm rough weather wind survival waterproof',
};

export const INDEX_COLORS: Record<string, string> = {
  'Equipment':   '#3B82F6',
  'Apparel':     '#10B981',
  'Protection':  '#F59E0B',
  'Accessories': '#8B5CF6',
};

export const INDEX_LABELS: Record<string, string> = {
  'Equipment':   'Equipment',
  'Apparel':     'Apparel',
  'Protection':  'Protection',
  'Accessories': 'Accessories',
};

export const PRODUCT_TYPE_EMOJI: Record<string, string> = {
  alpine_ski: '🎿',
  all_mountain_ski: '🎿',
  freeride_ski: '🎿',
  freestyle_ski: '🎿',
  all_mountain_snowboard: '🏂',
  freestyle_snowboard: '🏂',
  freeride_snowboard: '🏂',
  ski_boot: '👢',
  snowboard_boot: '👢',
  ski_binding: '🔩',
  snowboard_binding: '🔩',
  shell_jacket: '🧥',
  insulated_jacket: '🧥',
  ski_bib: '🩱',
  ski_pants: '👖',
  mid_layer_fleece: '🧶',
  down_mid_layer: '🧶',
  base_layer_top: '👕',
  base_layer_bottom: '🩲',
  ski_helmet: '⛑️',
  snowboard_helmet: '⛑️',
  ski_goggles: '🥽',
  snowboard_goggles: '🥽',
  back_protector: '🛡️',
  wrist_guard: '🦾',
  knee_pad: '🦵',
  ski_gloves: '🧤',
  snowboard_gloves: '🧤',
  mittens: '🧤',
  beanie: '🧢',
  face_mask: '😷',
  neck_gaiter: '🧣',
  avalanche_transceiver: '📡',
  avalanche_probe: '📏',
  avalanche_shovel: '🪣',
  ski_wax: '🕯️',
  edge_sharpener: '⚙️',
  // Title-case keys from the SNOWFIELD PRO catalog
  Jacket: '🧥',
  Skis: '🎿',
  Boots: '👢',
  Bindings: '🔩',
  Helmet: '⛑️',
  Goggles: '🥽',
  Pants: '👖',
  Gloves: '🧤',
  Gaiter: '🧣',
  'Back Protector': '🛡️',
  Backpack: '🎒',
  'Base Layer': '👕',
};

// Map product_type values to image filenames in /product-images/
export const PRODUCT_TYPE_IMAGE: Record<string, string> = {
  Jacket: 'shell_jacket',
  Skis: 'freeride_ski',
  Ski: 'freeride_ski',
  Boots: 'ski_boot',
  Boot: 'ski_boot',
  Bindings: 'ski_binding',
  Binding: 'ski_binding',
  Helmet: 'ski_helmet',
  Goggles: 'ski_goggles',
  Goggle: 'ski_goggles',
  Pants: 'ski_pants',
  Gloves: 'ski_gloves',
  Gaiter: 'neck_gaiter',
  'Back Protector': 'back_protector',
  Protector: 'back_protector',
  Backpack: 'back_protector',
  'Base Layer': 'base_layer_top',
  Fleece: 'mid_layer_fleece',
  Guards: 'knee_pad',
  Pole: 'alpine_ski',
  Airbag: 'avalanche_transceiver',
};

export const SKILL_BADGE: Record<string, string> = {
  Beginner: 'bg-green-100 text-green-800',
  Intermediate: 'bg-blue-100 text-blue-800',
  Advanced: 'bg-orange-100 text-orange-800',
  Professional: 'bg-red-100 text-red-800',
};
