CREATE OR REPLACE TASK public.update_truck_inventories
COMMENT = '{ "description": "", "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 2,  "minor": 29,  "patch": "0-Pr.424" }, "attributes": {  "component": "transact",  "convertedOn": "05/26/2026",  "domain": "no-domain-provided",  "migrationid": "JmWeAWK07nK+5zZKD9nimA==" }}'
CONFIG = $${
  "package": {
    "User_SpecialNote": {"value": "", "type": "VARCHAR", "is_parameter": false}
  }
}$$
AS
BEGIN
   LET config VARCHAR := SYSTEM$GET_TASK_GRAPH_CONFIG('package');
   LET scope VARCHAR := 'update_truck_inventories';
   CALL public.ClearVariables(:scope);
   CALL public.InitVariablesFromConfig(:scope, :config);
END;
CREATE OR REPLACE TASK public.update_truck_inventories_script_task
WAREHOUSE=DUMMY_WAREHOUSE
AFTER public.update_truck_inventories
AS
BEGIN
   ---- Start block 'Package\Script Task'
   !!!RESOLVE EWI!!! /*** SSC-EWI-SSIS0004 - SSIS CONTROL FLOW ELEMENT Microsoft.ScriptTask CANNOT BE CONVERTED TO SNOWFLAKE SCRIPTING. ***/!!!
   --<Executable ExecutableType="Microsoft.ScriptTask" refId="Package\Script Task" ThreadHint="0" LocaleID="-1" Description="Script Task" DTSID="{C46640C3-40FB-4486-85C4-E5EC65C40AC0}" CreationName="Microsoft.ScriptTask" ObjectName="Script Task">
   --  <EventHandlers />
   --  <ScriptProject Name="ST_e380224511f54e3cbc33412c4b9e9ede" VSTAMajorVersion="16" VSTAMinorVersion="0" Language="CSharp" ReadWriteVariables="User::SpecialNote">
   --    <ProjectItem Name="Properties\Resources.resx" Encoding="UTF8">&lt;?xml version="1.0" encoding="utf-8"?&gt;
   --&lt;root&gt;
   --  &lt;!-- 
   --    Microsoft ResX Schema 
   --    Version 2.0
   --    The primary goals of this format is to allow a simple XML format 
   --    that is mostly human readable. The generation and parsing of the 
   --    various data types are done through the TypeConverter classes 
   --    associated with the data types.
   --    Example:
   --    ... ado.net/XML headers &amp; schema ...
   --    &lt;resheader name="resmimetype"&gt;text/microsoft-resx&lt;/resheader&gt;
   --    &lt;resheader name="version"&gt;2.0&lt;/resheader&gt;
   --    &lt;resheader name="reader"&gt;System.Resources.ResXResourceReader, System.Windows.Forms, ...&lt;/resheader&gt;
   --    &lt;resheader name="writer"&gt;System.Resources.ResXResourceWriter, System.Windows.Forms, ...&lt;/resheader&gt;
   --    &lt;data name="Name1"&gt;&lt;value&gt;this is my long string&lt;/value&gt;&lt;comment&gt;this is a comment&lt;/comment&gt;&lt;/data&gt;
   --    &lt;data name="Color1" type="System.Drawing.Color, System.Drawing"&gt;Blue&lt;/data&gt;
   --    &lt;data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64"&gt;
   --        &lt;value&gt;[base64 mime encoded serialized .NET Framework object]&lt;/value&gt;
   --    &lt;/data&gt;
   --    &lt;data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64"&gt;
   --        &lt;value&gt;[base64 mime encoded string representing a byte array form of the .NET Framework object]&lt;/value&gt;
   --        &lt;comment&gt;This is a comment&lt;/comment&gt;
   --    &lt;/data&gt;
   --    There are any number of "resheader" rows that contain simple 
   --    name/value pairs.
   --    Each data row contains a name, and value. The row also contains a 
   --    type or mimetype. Type corresponds to a .NET class that support 
   --    text/value conversion through the TypeConverter architecture. 
   --    Classes that don't support this are serialized and stored with the 
   --    mimetype set.
   --    The mimetype is used for serialized objects, and tells the 
   --    ResXResourceReader how to depersist the object. This is currently not 
   --    extensible. For a given mimetype the value must be set accordingly:
   --    Note - application/x-microsoft.net.object.binary.base64 is the format 
   --    that the ResXResourceWriter will generate, however the reader can 
   --    read any of the formats listed below.
   --    mimetype: application/x-microsoft.net.object.binary.base64
   --    value   : The object must be serialized with 
   --            : System.Serialization.Formatters.Binary.BinaryFormatter
   --            : and then encoded with base64 encoding.
   --    mimetype: application/x-microsoft.net.object.soap.base64
   --    value   : The object must be serialized with 
   --            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
   --            : and then encoded with base64 encoding.
   --    mimetype: application/x-microsoft.net.object.bytearray.base64
   --    value   : The object must be serialized into a byte array 
   --            : using a System.ComponentModel.TypeConverter
   --            : and then encoded with base64 encoding.
   --    --&gt;
   --  &lt;xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"&gt;
   --    &lt;xsd:element name="root" msdata:IsDataSet="true"&gt;
   --      &lt;xsd:complexType&gt;
   --        &lt;xsd:choice maxOccurs="unbounded"&gt;
   --          &lt;xsd:element name="metadata"&gt;
   --            &lt;xsd:complexType&gt;
   --              &lt;xsd:sequence&gt;
   --                &lt;xsd:element name="value" type="xsd:string" minOccurs="0" /&gt;
   --              &lt;/xsd:sequence&gt;
   --              &lt;xsd:attribute name="name" type="xsd:string" /&gt;
   --              &lt;xsd:attribute name="type" type="xsd:string" /&gt;
   --              &lt;xsd:attribute name="mimetype" type="xsd:string" /&gt;
   --            &lt;/xsd:complexType&gt;
   --          &lt;/xsd:element&gt;
   --          &lt;xsd:element name="assembly"&gt;
   --            &lt;xsd:complexType&gt;
   --              &lt;xsd:attribute name="alias" type="xsd:string" /&gt;
   --              &lt;xsd:attribute name="name" type="xsd:string" /&gt;
   --            &lt;/xsd:complexType&gt;
   --          &lt;/xsd:element&gt;
   --          &lt;xsd:element name="data"&gt;
   --            &lt;xsd:complexType&gt;
   --              &lt;xsd:sequence&gt;
   --                &lt;xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" /&gt;
   --                &lt;xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" /&gt;
   --              &lt;/xsd:sequence&gt;
   --              &lt;xsd:attribute name="name" type="xsd:string" msdata:Ordinal="1" /&gt;
   --              &lt;xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" /&gt;
   --              &lt;xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" /&gt;
   --            &lt;/xsd:complexType&gt;
   --          &lt;/xsd:element&gt;
   --          &lt;xsd:element name="resheader"&gt;
   --            &lt;xsd:complexType&gt;
   --              &lt;xsd:sequence&gt;
   --                &lt;xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" /&gt;
   --              &lt;/xsd:sequence&gt;
   --              &lt;xsd:attribute name="name" type="xsd:string" use="required" /&gt;
   --            &lt;/xsd:complexType&gt;
   --          &lt;/xsd:element&gt;
   --        &lt;/xsd:choice&gt;
   --      &lt;/xsd:complexType&gt;
   --    &lt;/xsd:element&gt;
   --  &lt;/xsd:schema&gt;
   --  &lt;resheader name="resmimetype"&gt;
   --    &lt;value&gt;text/microsoft-resx&lt;/value&gt;
   --  &lt;/resheader&gt;
   --  &lt;resheader name="version"&gt;
   --    &lt;value&gt;2.0&lt;/value&gt;
   --  &lt;/resheader&gt;
   --  &lt;resheader name="reader"&gt;
   --    &lt;value&gt;System.Resources.ResXResourceReader, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&lt;/value&gt;
   --  &lt;/resheader&gt;
   --  &lt;resheader name="writer"&gt;
   --    &lt;value&gt;System.Resources.ResXResourceWriter, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&lt;/value&gt;
   --  &lt;/resheader&gt;
   --&lt;/root&gt;</ProjectItem>
   --    <ProjectItem Name="Properties\Settings.Designer.cs" Encoding="UTF8">//------------------------------------------------------------------------------
   --// &lt;auto-generated&gt;
   --//     This code was generated by a tool.
   --//
   --//     Changes to this file may cause incorrect behavior and will be lost if
   --//     the code is regenerated.
   --// &lt;/auto-generated&gt;
   --//------------------------------------------------------------------------------
   --[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Settings.get_Default():ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Sett" +
   --    "ings")]
   --namespace ST_e380224511f54e3cbc33412c4b9e9ede.Properties {
   --    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
   --        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
   --        private static Settings defaultInstance = new Settings();
   --        public static Settings Default {
   --            get {
   --                return defaultInstance;
   --            }
   --        }
   --    }
   --}</ProjectItem>
   --    <ProjectItem Name="ST_e380224511f54e3cbc33412c4b9e9ede.csproj" Encoding="UTF8">&lt;?xml version="1.0" encoding="utf-8"?&gt;
   --&lt;Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"&gt;
   --  &lt;PropertyGroup&gt;
   --    &lt;ProjectTypeGuids&gt;{30D016F9-3734-4E33-A861-5E7D899E18F3};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;
   --    &lt;Configuration Condition=" '$(Configuration)' == '' "&gt;Debug&lt;/Configuration&gt;
   --    &lt;Platform Condition=" '$(Platform)' == '' "&gt;AnyCPU&lt;/Platform&gt;
   --    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
   --    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
   --    &lt;ProjectGuid&gt;{232A7726-28AD-4D55-9C85-3EF5A66B9FF9}&lt;/ProjectGuid&gt;
   --    &lt;OutputType&gt;Library&lt;/OutputType&gt;
   --    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
   --    &lt;RootNamespace&gt;ST_e380224511f54e3cbc33412c4b9e9ede&lt;/RootNamespace&gt;
   --    &lt;AssemblyName&gt;ST_e380224511f54e3cbc33412c4b9e9ede&lt;/AssemblyName&gt;
   --    &lt;TargetFrameworkVersion&gt;v4.7&lt;/TargetFrameworkVersion&gt;
   --    &lt;FileAlignment&gt;512&lt;/FileAlignment&gt;
   --    &lt;ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch&gt;true&lt;/ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch&gt;
   --    &lt;TargetFrameworkProfile&gt;&lt;/TargetFrameworkProfile&gt;
   --  &lt;/PropertyGroup&gt;
   --  &lt;PropertyGroup Condition=" '$(Configuration)' == 'Debug' "&gt;
   --    &lt;DebugSymbols&gt;true&lt;/DebugSymbols&gt;
   --    &lt;DebugType&gt;full&lt;/DebugType&gt;
   --    &lt;Optimize&gt;false&lt;/Optimize&gt;
   --    &lt;OutputPath&gt;.\bin\Debug\&lt;/OutputPath&gt;
   --    &lt;EnableUnmanagedDebugging&gt;false&lt;/EnableUnmanagedDebugging&gt;
   --    &lt;DefineConstants&gt;DEBUG;TRACE&lt;/DefineConstants&gt;
   --    &lt;ErrorReport&gt;prompt&lt;/ErrorReport&gt;
   --    &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
   --  &lt;/PropertyGroup&gt;
   --  &lt;PropertyGroup Condition=" '$(Configuration)' == 'Release' "&gt;
   --    &lt;DebugSymbols&gt;false&lt;/DebugSymbols&gt;
   --    &lt;Optimize&gt;true&lt;/Optimize&gt;
   --    &lt;OutputPath&gt;.\bin\Release\&lt;/OutputPath&gt;
   --    &lt;EnableUnmanagedDebugging&gt;false&lt;/EnableUnmanagedDebugging&gt;
   --    &lt;DefineConstants&gt;TRACE&lt;/DefineConstants&gt;
   --    &lt;ErrorReport&gt;prompt&lt;/ErrorReport&gt;
   --    &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
   --  &lt;/PropertyGroup&gt;
   --  &lt;ItemGroup&gt;
   --    &lt;Reference Include="System" /&gt;
   --    &lt;Reference Include="System.Data" /&gt;
   --    &lt;Reference Include="System.Windows.Forms" /&gt;
   --    &lt;Reference Include="System.Xml" /&gt;
   --    &lt;Reference Include="Microsoft.SqlServer.ManagedDTS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" /&gt;
   --    &lt;Reference Include="Microsoft.SqlServer.ScriptTask, Version=16.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" /&gt;
   --  &lt;/ItemGroup&gt;
   --  &lt;ItemGroup&gt;
   --    &lt;AppDesigner Include="Properties\" /&gt;
   --    &lt;Compile Include="Properties\AssemblyInfo.cs"&gt;
   --      &lt;SubType&gt;Code&lt;/SubType&gt;
   --    &lt;/Compile&gt;
   --    &lt;EmbeddedResource Include="Properties\Resources.resx"&gt;
   --      &lt;Generator&gt;ResXFileCodeGenerator&lt;/Generator&gt;
   --      &lt;LastGenOutput&gt;Resources.Designer.cs&lt;/LastGenOutput&gt;
   --    &lt;/EmbeddedResource&gt;
   --    &lt;Compile Include="Properties\Resources.Designer.cs"&gt;
   --      &lt;AutoGen&gt;True&lt;/AutoGen&gt;
   --      &lt;DependentUpon&gt;Resources.resx&lt;/DependentUpon&gt;
   --    &lt;/Compile&gt;
   --    &lt;None Include="Properties\Settings.settings"&gt;
   --      &lt;Generator&gt;SettingsSingleFileGenerator&lt;/Generator&gt;
   --      &lt;LastGenOutput&gt;Settings.Designer.cs&lt;/LastGenOutput&gt;
   --    &lt;/None&gt;
   --    &lt;Compile Include="Properties\Settings.Designer.cs"&gt;
   --      &lt;AutoGen&gt;True&lt;/AutoGen&gt;
   --      &lt;DependentUpon&gt;Settings.settings&lt;/DependentUpon&gt;
   --    &lt;/Compile&gt;
   --    &lt;Compile Include="ScriptMain.cs"&gt;
   --      &lt;SubType&gt;Code&lt;/SubType&gt;
   --    &lt;/Compile&gt;
   --  &lt;/ItemGroup&gt;
   --  &lt;!-- Include the build rules for a C# project.--&gt;
   --  &lt;Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" /&gt;
   --  &lt;ProjectExtensions&gt;
   --    &lt;VisualStudio&gt;
   --      &lt;FlavorProperties GUID="{30D016F9-3734-4E33-A861-5E7D899E18F3}"&gt;
   --        &lt;ProjectProperties HostName="VSTAHostName" HostPackage="{B3A685AA-7EAF-4BC6-9940-57959FA5AC07}" ApplicationType="usd" Language="cs" TemplatesPath="" /&gt;
   --        &lt;Host Name="ScriptTask" /&gt;
   --        &lt;ProjectClient&gt;
   --          &lt;HostIdentifier&gt;SSIS_ST160&lt;/HostIdentifier&gt;
   --        &lt;/ProjectClient&gt;
   --      &lt;/FlavorProperties&gt;
   --    &lt;/VisualStudio&gt;
   --  &lt;/ProjectExtensions&gt;
   --&lt;/Project&gt;</ProjectItem>
   --    <ProjectItem Name="ScriptMain.cs" Encoding="UTF8">#region Help:  Introduction to the script task
   --/* The Script Task allows you to perform virtually any operation that can be accomplished in
   -- * a .Net application within the context of an Integration Services control flow. 
   -- * 
   -- * Expand the other regions which have "Help" prefixes for examples of specific ways to use
   -- * Integration Services features within this script task. */
   --#endregion
   --#region Namespaces
   --using System;
   --using System.Data;
   --using Microsoft.SqlServer.Dts.Runtime;
   --using System.Windows.Forms;
   --#endregion
   --namespace ST_e380224511f54e3cbc33412c4b9e9ede
   --{
   --    /// &lt;summary&gt;
   --    /// ScriptMain is the entry point class of the script.  Do not change the name, attributes,
   --    /// or parent of this class.
   --    /// &lt;/summary&gt;
   --	[Microsoft.SqlServer.Dts.Tasks.ScriptTask.SSISScriptTaskEntryPointAttribute]
   --	public partial class ScriptMain : Microsoft.SqlServer.Dts.Tasks.ScriptTask.VSTARTScriptObjectModelBase
   --	{
   --        #region Help:  Using Integration Services variables and parameters in a script
   --        /* To use a variable in this script, first ensure that the variable has been added to 
   --         * either the list contained in the ReadOnlyVariables property or the list contained in 
   --         * the ReadWriteVariables property of this script task, according to whether or not your
   --         * code needs to write to the variable.  To add the variable, save this script, close this instance of
   --         * Visual Studio, and update the ReadOnlyVariables and 
   --         * ReadWriteVariables properties in the Script Transformation Editor window.
   --         * To use a parameter in this script, follow the same steps. Parameters are always read-only.
   --         * 
   --         * Example of reading from a variable:
   --         *  DateTime startTime = (DateTime) Dts.Variables["System::StartTime"].Value;
   --         * 
   --         * Example of writing to a variable:
   --         *  Dts.Variables["User::myStringVariable"].Value = "new value";
   --         * 
   --         * Example of reading from a package parameter:
   --         *  int batchId = (int) Dts.Variables["$Package::batchId"].Value;
   --         *  
   --         * Example of reading from a project parameter:
   --         *  int batchId = (int) Dts.Variables["$Project::batchId"].Value;
   --         * 
   --         * Example of reading from a sensitive project parameter:
   --         *  int batchId = (int) Dts.Variables["$Project::batchId"].GetSensitiveValue();
   --         * */
   --        #endregion
   --        #region Help:  Firing Integration Services events from a script
   --        /* This script task can fire events for logging purposes.
   --         * 
   --         * Example of firing an error event:
   --         *  Dts.Events.FireError(18, "Process Values", "Bad value", "", 0);
   --         * 
   --         * Example of firing an information event:
   --         *  Dts.Events.FireInformation(3, "Process Values", "Processing has started", "", 0, ref fireAgain)
   --         * 
   --         * Example of firing a warning event:
   --         *  Dts.Events.FireWarning(14, "Process Values", "No values received for input", "", 0);
   --         * */
   --        #endregion
   --        #region Help:  Using Integration Services connection managers in a script
   --        /* Some types of connection managers can be used in this script task.  See the topic 
   --         * "Working with Connection Managers Programatically" for details.
   --         * 
   --         * Example of using an ADO.Net connection manager:
   --         *  object rawConnection = Dts.Connections["Sales DB"].AcquireConnection(Dts.Transaction);
   --         *  SqlConnection myADONETConnection = (SqlConnection)rawConnection;
   --         *  //Use the connection in some code here, then release the connection
   --         *  Dts.Connections["Sales DB"].ReleaseConnection(rawConnection);
   --         *
   --         * Example of using a File connection manager
   --         *  object rawConnection = Dts.Connections["Prices.zip"].AcquireConnection(Dts.Transaction);
   --         *  string filePath = (string)rawConnection;
   --         *  //Use the connection in some code here, then release the connection
   --         *  Dts.Connections["Prices.zip"].ReleaseConnection(rawConnection);
   --         * */
   --        #endregion
   --		/// &lt;summary&gt;
   --        /// This method is called when this script task executes in the control flow.
   --        /// Before returning from this method, set the value of Dts.TaskResult to indicate success or failure.
   --        /// To open Help, press F1.
   --        /// &lt;/summary&gt;
   --		public void Main()
   --		{
   --            // TODO: Add your code here
   --            var note = "This is a " + "special note";
   --            for (var i = 0; i &lt; 3; i++)
   --            {
   --                note += "!";
   --            }
   --            Dts.Variables["User::SpecialNote"].Value = note;
   --            Dts.TaskResult = (int)ScriptResults.Success;
   --		}
   --        #region ScriptResults declaration
   --        /// &lt;summary&gt;
   --        /// This enum provides a convenient shorthand within the scope of this class for setting the
   --        /// result of the script.
   --        /// 
   --        /// This code was generated automatically.
   --        /// &lt;/summary&gt;
   --        enum ScriptResults
   --        {
   --            Success = Microsoft.SqlServer.Dts.Runtime.DTSExecResult.Success,
   --            Failure = Microsoft.SqlServer.Dts.Runtime.DTSExecResult.Failure
   --        };
   --        #endregion
   --	}
   --}</ProjectItem>
   --    <ProjectItem Name="Project" Encoding="UTF16LE">&lt;?xml version="1.0" encoding="UTF-16" standalone="yes"?&gt;
   --&lt;c:Project xmlns:c="http://schemas.microsoft.com/codeprojectml/2010/08/main" xmlns:msb="http://schemas.microsoft.com/developer/msbuild/2003" runtimeVersion="4.0" schemaVersion="1.0"&gt;
   --  &lt;msb:PropertyGroup&gt;
   --    &lt;msb:CodeName&gt;ST_e380224511f54e3cbc33412c4b9e9ede&lt;/msb:CodeName&gt;
   --    &lt;msb:Language&gt;msBuild&lt;/msb:Language&gt;
   --    &lt;msb:DisplayName&gt;ST_e380224511f54e3cbc33412c4b9e9ede&lt;/msb:DisplayName&gt;
   --    &lt;msb:ProjectId&gt;{54E0FCBF-2756-42BD-BBE5-9B49171B0DCF}&lt;/msb:ProjectId&gt;
   --  &lt;/msb:PropertyGroup&gt;
   --  &lt;msb:ItemGroup&gt;
   --    &lt;msb:Project Include="ST_e380224511f54e3cbc33412c4b9e9ede.csproj" /&gt;
   --    &lt;msb:File Include="Properties\Resources.Designer.cs" /&gt;
   --    &lt;msb:File Include="Properties\Settings.settings" /&gt;
   --    &lt;msb:File Include="Properties\AssemblyInfo.cs" /&gt;
   --    &lt;msb:File Include="Properties\Resources.resx" /&gt;
   --    &lt;msb:File Include="Properties\Settings.Designer.cs" /&gt;
   --    &lt;msb:File Include="ScriptMain.cs" /&gt;
   --  &lt;/msb:ItemGroup&gt;
   --&lt;/c:Project&gt;</ProjectItem>
   --    <ProjectItem Name="Properties\AssemblyInfo.cs" Encoding="UTF8">using System.Reflection;
   --using System.Runtime.CompilerServices;
   --//
   --// General Information about an assembly is controlled through the following 
   --// set of attributes. Change these attribute values to modify the information
   --// associated with an assembly.
   --//
   --[assembly: AssemblyTitle("ST_e380224511f54e3cbc33412c4b9e9ede")]
   --[assembly: AssemblyDescription("")]
   --[assembly: AssemblyConfiguration("")]
   --[assembly: AssemblyCompany("Amazon.com")]
   --[assembly: AssemblyProduct("ST_e380224511f54e3cbc33412c4b9e9ede")]
   --[assembly: AssemblyCopyright("Copyright @ Amazon.com 2026")]
   --[assembly: AssemblyTrademark("")]
   --[assembly: AssemblyCulture("")]
   --//
   --// Version information for an assembly consists of the following four values:
   --//
   --//      Major Version
   --//      Minor Version 
   --//      Build Number
   --//      Revision
   --//
   --// You can specify all the values or you can default the Revision and Build Numbers 
   --// by using the '*' as shown below:
   --[assembly: AssemblyVersion("1.0.*")]</ProjectItem>
   --    <ProjectItem Name="Properties\Settings.settings" Encoding="UTF8">&lt;?xml version='1.0' encoding='iso-8859-1'?&gt;
   --&lt;SettingsFile xmlns="uri:settings" CurrentProfile="(Default)"&gt;
   --  &lt;Profiles&gt;
   --    &lt;Profile Name="(Default)" /&gt;
   --  &lt;/Profiles&gt;
   --  &lt;Settings /&gt;
   --&lt;/SettingsFile&gt;</ProjectItem>
   --    <ProjectItem Name="Properties\Resources.Designer.cs" Encoding="UTF8">//------------------------------------------------------------------------------
   --// &lt;auto-generated&gt;
   --//     This code was generated by a tool.
   --//
   --//     Changes to this file may cause incorrect behavior and will be lost if
   --//     the code is regenerated.
   --// &lt;/auto-generated&gt;
   --//------------------------------------------------------------------------------
   --[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Resources.get_ResourceManager():System.Resources.Resou" +
   --    "rceManager")]
   --[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Resources.get_Culture():System.Globalization.CultureIn" +
   --    "fo")]
   --[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Resources.set_Culture(System.Globalization.CultureInfo" +
   --    "):Void")]
   --namespace ST_e380224511f54e3cbc33412c4b9e9ede.Properties {
   --    /// &lt;summary&gt;
   --    ///   A strongly-typed resource class, for looking up localized strings, etc.
   --    /// &lt;/summary&gt;
   --    // This class was auto-generated by the StronglyTypedResourceBuilder
   --    // class via a tool like ResGen or Visual Studio.
   --    // To add or remove a member, edit your .ResX file then rerun ResGen
   --    // with the /str option, or rebuild your VS project.
   --    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
   --    internal class Resources {
   --        private static global::System.Resources.ResourceManager resourceMan;
   --        private static global::System.Globalization.CultureInfo resourceCulture;
   --        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
   --        internal Resources() {
   --        }
   --        /// &lt;summary&gt;
   --        ///   Returns the cached ResourceManager instance used by this class.
   --        /// &lt;/summary&gt;
   --        [global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
   --        internal static global::System.Resources.ResourceManager ResourceManager {
   --            get {
   --                if ((resourceMan == null)) {
   --                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST_e380224511f54e3cbc33412c4b9e9ede.Properties.Resources", typeof(Resources).Assembly);
   --                    resourceMan = temp;
   --                }
   --                return resourceMan;
   --            }
   --        }
   --        /// &lt;summary&gt;
   --        ///   Overrides the current thread's CurrentUICulture property for all
   --        ///   resource lookups using this strongly typed resource class.
   --        /// &lt;/summary&gt;
   --        [global::System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
   --        internal static global::System.Globalization.CultureInfo Culture {
   --            get {
   --                return resourceCulture;
   --            }
   --            set {
   --                resourceCulture = value;
   --            }
   --        }
   --    }
   --}</ProjectItem>
   --    <BinaryItem Name="ST_e380224511f54e3cbc33412c4b9e9ede.dll">TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v
   --ZGUuDQ0KJAAAAAAAAABQRQAATAEDAAJyDGoAAAAAAAAAAOAAIiALATAAABAAAAAIAAAAAAAA/i0A
   --AAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAA
   --ABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAKwtAABPAAAAAEAAAKAEAAAAAAAAAAAAAAAAAAAA
   --AAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAABA4AAAAgAAAAEAAAAAIA
   --AAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAKAEAAAAQAAAAAYAAAASAAAAAAAAAAAAAAAAAABAAABA
   --LnJlbG9jAAAMAAAAAGAAAAACAAAAGAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADg
   --LQAAAAAAAEgAAAACAAUACCEAAOwLAAABAAAAAAAAAPQsAAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwAgBGAAAAAQAAEXIBAABwChYLKxAGci8AAHAoEAAACgoH
   --F1gLBxky7AIoEQAACm8SAAAKcjMAAHBvEwAACgZvFAAACgIoEQAAChZvFQAACioeAigWAAAKKh4C
   --KBcAAAoqrn4BAAAELR5yVwAAcNADAAACKBgAAApvGQAACnMaAAAKgAEAAAR+AQAABCoafgIAAAQq
   --HgKAAgAABCoafgMAAAQqHgIoGwAACioucwgAAAaAAwAABCpCU0pCAQABAAAAAAAMAAAAdjQuMC4z
   --MDMxOQAAAAAFAGwAAADEAwAAI34AADAEAABgBQAAI1N0cmluZ3MAAAAAkAkAAMwAAAAjVVMAXAoA
   --ABAAAAAjR1VJRAAAAGwKAACAAQAAI0Jsb2IAAAAAAAAAAgAAAVcdogEJAwAAAPoBMwAWAAABAAAA
   --HgAAAAUAAAAGAAAACQAAAAEAAAAbAAAAAgAAABAAAAABAAAAAgAAAAMAAAAEAAAAAQAAAAQAAAAB
   --AAAAAQAAAAAAcwMBAAAAAAAGACUCQwQGALQCQwQGAHEBMAQPALcEAAAGAJ4B8QMGAAgC8QMGAOkB
   --8QMGAJsC8QMGAEUC8QMGAF4C8QMGALUB8QMGANAB4gIKAHkCIgMKAPAAIgMGAKsDpAMGAFQBMAQG
   --ADEFpAMGABMEYwQGAAME3AMOACQBXQMOAIUBXQMOAAwBxwMGADkBQwQGAPwCpAMKAEsDIgMSAPkE
   --mwASAG4AmwAGALsApAMGAHcApAMGAFcF8QMAAAAAAQAAAAAAAQABAAEAEAC8A0oAOQABAAEAAAAQ
   --AGoExgRFAAEAAwAAARAAAwXGBFkAAwAHAAMBAAAcBQAAPQAEAAoAEQCwA2oAEQDgAG4AEQA6AHIA
   --BgYpAHYAVoAMBXkAVoDAAHkAUCAAAAAAhgDCAwYAAQCiIAAAAACGGCMEBgABAKogAAAAAIMYIwQG
   --AAEAsiAAAAAAkwgPBH0AAQDeIAAAAACTCMgAggABAOUgAAAAAJMI1ACHAAEA7SAAAAAAlgg4BY0A
   --AgD0IAAAAACGGCMEBgACAPwgAAAAAJEYKQSSAAIAAAABANwCCQAjBAEAEQAjBAYAGQAjBAoAKQAj
   --BBAAMQAjBBAAOQAjBBAAQQAjBBAASQAjBBAAUQAjBBAAWQAjBBAAYQAjBBAAaQAjBAYAgQAjBAYA
   --qQAjBBUAuQAjBAYAwQAqBSAAcQAUBSYAyQD1BCsA0QCbAzAA2QDSAjYAyQBEBQEAcQAjBAYAiQAj
   --BAYA4QCJADsA4QBTBUIAkQAjBEcAsQAjBAYACAAUAGAACAAYAGUAKQBzAM0ALgALAKUALgATAK4A
   --LgAbAM0ALgAjANYALgArAP8ALgAzAP8ALgA7AAUBLgBDANYALgBLABUBLgBTAP8ALgBbADYBQwBj
   --AGUASQBzAM0AYQB7AGUAYwBrAGUAGwADAAEABAADAAAAEwSWAAAA6ACbAAAAPAWgAAIABAADAAIA
   --BQAFAAEABgAFAAIABwAHAASAAAABAAAAoyUAZQAAAAAAAEoAAAAEAAAAAAAAAAAAAABOADEAAAAA
   --ABAAAAAAAAAAAAAAAFcAAwMAAAAABAAAAAAAAAAAAAAATgCkAwAAAAAQAAAAAAAAAAAAAABXAAoA
   --AAAAAAAAAAABAAAAdAQAAAUAAgAAAAAAADxNb2R1bGU+AE1pY3Jvc29mdC5TcWxTZXJ2ZXIuTWFu
   --YWdlZERUUwB2YWx1ZV9fAG1zY29ybGliAGRlZmF1bHRJbnN0YW5jZQBTVF9lMzgwMjI0NTExZjU0
   --ZTNjYmMzMzQxMmM0YjllOWVkZQBWYXJpYWJsZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJv
   --bUhhbmRsZQBNaWNyb3NvZnQuU3FsU2VydmVyLkR0cy5SdW50aW1lAFR5cGUARmFpbHVyZQBnZXRf
   --Q3VsdHVyZQBzZXRfQ3VsdHVyZQByZXNvdXJjZUN1bHR1cmUAVlNUQVJUU2NyaXB0T2JqZWN0TW9k
   --ZWxCYXNlAEFwcGxpY2F0aW9uU2V0dGluZ3NCYXNlAEVkaXRvckJyb3dzYWJsZVN0YXRlAENvbXBp
   --bGVyR2VuZXJhdGVkQXR0cmlidXRlAERlYnVnZ2VyTm9uVXNlckNvZGVBdHRyaWJ1dGUARGVidWdn
   --YWJsZUF0dHJpYnV0ZQBFZGl0b3JCcm93c2FibGVBdHRyaWJ1dGUAQXNzZW1ibHlUaXRsZUF0dHJp
   --YnV0ZQBBc3NlbWJseVRyYWRlbWFya0F0dHJpYnV0ZQBUYXJnZXRGcmFtZXdvcmtBdHRyaWJ1dGUA
   --QXNzZW1ibHlDb25maWd1cmF0aW9uQXR0cmlidXRlAEFzc2VtYmx5RGVzY3JpcHRpb25BdHRyaWJ1
   --dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1
   --dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUAU1NJU1NjcmlwdFRhc2tFbnRyeVBvaW50QXR0
   --cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJp
   --YnV0ZQBzZXRfVmFsdWUAdmFsdWUAU3lzdGVtLlJ1bnRpbWUuVmVyc2lvbmluZwBTdHJpbmcATWlj
   --cm9zb2Z0LlNxbFNlcnZlci5TY3JpcHRUYXNrAE1pY3Jvc29mdC5TcWxTZXJ2ZXIuRHRzLlRhc2tz
   --LlNjcmlwdFRhc2sAU2NyaXB0T2JqZWN0TW9kZWwAU3lzdGVtLkNvbXBvbmVudE1vZGVsAFNUX2Uz
   --ODAyMjQ1MTFmNTRlM2NiYzMzNDEyYzRiOWU5ZWRlLmRsbABnZXRfSXRlbQBTeXN0ZW0ARW51bQBy
   --ZXNvdXJjZU1hbgBTY3JpcHRNYWluAFN5c3RlbS5Db25maWd1cmF0aW9uAFN5c3RlbS5HbG9iYWxp
   --emF0aW9uAFN5c3RlbS5SZWZsZWN0aW9uAEN1bHR1cmVJbmZvAGdldF9SZXNvdXJjZU1hbmFnZXIA
   --LmN0b3IALmNjdG9yAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNl
   --cnZpY2VzAFN5c3RlbS5SZXNvdXJjZXMAU1RfZTM4MDIyNDUxMWY1NGUzY2JjMzM0MTJjNGI5ZTll
   --ZGUuUHJvcGVydGllcy5SZXNvdXJjZXMucmVzb3VyY2VzAERlYnVnZ2luZ01vZGVzAFNUX2UzODAy
   --MjQ1MTFmNTRlM2NiYzMzNDEyYzRiOWU5ZWRlLlByb3BlcnRpZXMAZ2V0X1ZhcmlhYmxlcwBTZXR0
   --aW5ncwBTdWNjZXNzAGdldF9EdHMAU2NyaXB0UmVzdWx0cwBDb25jYXQAT2JqZWN0AGdldF9EZWZh
   --dWx0AHNldF9UYXNrUmVzdWx0AGdldF9Bc3NlbWJseQAALVQAaABpAHMAIABpAHMAIABhACAAcwBw
   --AGUAYwBpAGEAbAAgAG4AbwB0AGUAAAMhAAAjVQBzAGUAcgA6ADoAUwBwAGUAYwBpAGEAbABOAG8A
   --dABlAABxUwBUAF8AZQAzADgAMAAyADIANAA1ADEAMQBmADUANABlADMAYwBiAGMAMwAzADQAMQAy
   --AGMANABiADkAZQA5AGUAZABlAC4AUAByAG8AcABlAHIAdABpAGUAcwAuAFIAZQBzAG8AdQByAGMA
   --ZQBzAAAAAABmRCRNRRNZQbodIt3+afUXAAQgAQEIAyAAAQUgAQEREQQgAQEOBSABARFRBAcCDggF
   --AAIODg4EIAASZQQgABJpBSABEm0cBCABARwGAAEScRF1BCAAEnkGIAIBDhJ5CLd6XFYZNOCJCImE
   --Xc2AgMyRBAAAAAAEAQAAAAMGEkkDBhJNAwYSEAIGCAMGERQEAAASSQQAABJNBQABARJNBAAAEhAD
   --AAABBAgAEkkECAASTQQIABIQCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dz
   --AQgBAAIAAAAAACgBACNTVF9lMzgwMjI0NTExZjU0ZTNjYmMzMzQxMmM0YjllOWVkZQAABQEAAAAA
   --DwEACkFtYXpvbi5jb20AACABABtDb3B5cmlnaHQgQCBBbWF6b24uY29tIDIwMjYAAEkBABouTkVU
   --RnJhbWV3b3JrLFZlcnNpb249djQuNwEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUSLk5FVCBGcmFt
   --ZXdvcmsgNC43tAAAAM7K774BAAAAkQAAAGxTeXN0ZW0uUmVzb3VyY2VzLlJlc291cmNlUmVhZGVy
   --LCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRv
   --a2VuPWI3N2E1YzU2MTkzNGUwODkjU3lzdGVtLlJlc291cmNlcy5SdW50aW1lUmVzb3VyY2VTZXQC
   --AAAAAAAAAAAAAABQQURQQURQtAAAANQtAAAAAAAAAAAAAO4tAAAAIAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAADgLQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAA
   --AABIAAAAWEAAAEIEAAAAAAAAAAAAAEIENAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBP
   --AAAAAAC9BO/+AAABAAAAAQAAZaMlAAABAABloyU/AAAAAAAAAAQAAAACAAAAAAAAAAAAAAAAAAAA
   --RAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBv
   --AG4AAAAAAAAAsASiAwAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAAB+AwAAAQAwADAA
   --MAAwADAANABiADAAAAAaAAEAAQBDAG8AbQBtAGUAbgB0AHMAAAAAAAAANgALAAEAQwBvAG0AcABh
   --AG4AeQBOAGEAbQBlAAAAAABBAG0AYQB6AG8AbgAuAGMAbwBtAAAAAABwACQAAQBGAGkAbABlAEQA
   --ZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAUwBUAF8AZQAzADgAMAAyADIANAA1ADEAMQBmADUANABl
   --ADMAYwBiAGMAMwAzADQAMQAyAGMANABiADkAZQA5AGUAZABlAAAAPgAPAAEARgBpAGwAZQBWAGUA
   --cgBzAGkAbwBuAAAAAAAxAC4AMAAuADkANgAzADUALgAyADUAOAA1ADYAAAAAAHAAKAABAEkAbgB0
   --AGUAcgBuAGEAbABOAGEAbQBlAAAAUwBUAF8AZQAzADgAMAAyADIANAA1ADEAMQBmADUANABlADMA
   --YwBiAGMAMwAzADQAMQAyAGMANABiADkAZQA5AGUAZABlAC4AZABsAGwAAABcABwAAQBMAGUAZwBh
   --AGwAQwBvAHAAeQByAGkAZwBoAHQAAABDAG8AcAB5AHIAaQBnAGgAdAAgAEAAIABBAG0AYQB6AG8A
   --bgAuAGMAbwBtACAAMgAwADIANgAAACoAAQABAEwAZQBnAGEAbABUAHIAYQBkAGUAbQBhAHIAawBz
   --AAAAAAAAAAAAeAAoAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAFMAVABfAGUA
   --MwA4ADAAMgAyADQANQAxADEAZgA1ADQAZQAzAGMAYgBjADMAMwA0ADEAMgBjADQAYgA5AGUAOQBl
   --AGQAZQAuAGQAbABsAAAAaAAkAAEAUAByAG8AZAB1AGMAdABOAGEAbQBlAAAAAABTAFQAXwBlADMA
   --OAAwADIAMgA0ADUAMQAxAGYANQA0AGUAMwBjAGIAYwAzADMANAAxADIAYwA0AGIAOQBlADkAZQBk
   --AGUAAABCAA8AAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADkANgAzADUA
   --LgAyADUAOAA1ADYAAAAAAEYADwABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAx
   --AC4AMAAuADkANgAzADUALgAyADUAOAA1ADYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAwAAAAAPgAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
   --AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</BinaryItem>
   --  </ScriptProject>
   --</Executable>
    ;
   ---- End block 'Package\Script Task'

END;

CREATE OR REPLACE TASK public.update_truck_inventories_update_inventory_truck1
WAREHOUSE=DUMMY_WAREHOUSE
AFTER public.update_truck_inventories_script_task
AS
BEGIN
   LET User_SpecialNote VARCHAR := public.GetControlVariableUDF('User_SpecialNote', 'update_truck_inventories') :: VARCHAR;
   ---- Start block 'Package\update_inventory_truck1'
   --** SSC-FDM-0007 - MISSING DEPENDENT OBJECT "TastyBytes.Inventory" **
   UPDATE TastyBytes.Inventory
      SET
         SupplierNotes = :User_SpecialNote
      WHERE
         TruckID = 1;
   ---- End block 'Package\update_inventory_truck1'

   CALL public.UpdateControlVariable('User_SpecialNote', 'update_truck_inventories', TO_VARIANT(:User_SpecialNote));
END;

CREATE OR REPLACE TASK public.update_truck_inventories_update_inventory_truck2
WAREHOUSE=DUMMY_WAREHOUSE
AFTER public.update_truck_inventories_script_task
AS
BEGIN
   LET User_SpecialNote VARCHAR := public.GetControlVariableUDF('User_SpecialNote', 'update_truck_inventories') :: VARCHAR;
   ---- Start block 'Package\update_inventory_truck2'
   --** SSC-FDM-0007 - MISSING DEPENDENT OBJECT "TastyBytes.Inventory" **
   UPDATE TastyBytes.Inventory
      SET
         SupplierNotes = :User_SpecialNote
      WHERE
         TruckID = 2;
   ---- End block 'Package\update_inventory_truck2'

   CALL public.UpdateControlVariable('User_SpecialNote', 'update_truck_inventories', TO_VARIANT(:User_SpecialNote));
END;

