name: snowpark-ml-hol
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.9
  - snowflake-snowpark-python=1.4.0
  #- snowflake-snowpark-python=1.5.0 : Add this back once it's in the channel; need to conda install for now: conda install -c anaconda snowflake-snowpark-python
  - pandas=1.5.3
  - xgboost==1.7.3
  - notebook=6.5.4
  - scikit-learn=1.2.2
  - cachetools=4.2.2
  - seaborn=0.12.2
  - matplotlib=3.7.1