name: Validate Markdown on PR and Push

on:
  push:
    paths:
      - "**.md"  # Only trigger for .md file changes
  pull_request:
    paths:
      - "**.md"  # Only trigger for .md file changes

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid shallow clone issues

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyYAML

      - name: Find changed Markdown files
        id: find-md-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_BRANCH="origin/${{ github.base_ref }}"
            FILES=$(git diff --name-only $BASE_BRANCH -- '*.md')
          else
            FILES=$(git diff --name-only HEAD~1 HEAD -- '*.md' || echo "")
          fi
          
          if [ -z "$FILES" ]; then
            echo "No markdown files to validate."
            exit 0
          fi
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Run Markdown validation
        run: python .github/scripts/validate_markdown.py $FILES
