name: Validate Markdown on PR and Push

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (only latest commit)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch at least 2 commits to avoid "HEAD^" errors

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyYAML

      - name: Find changed Markdown files
        id: find-md-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            FILES=$(git diff --name-only origin/${{ github.base_ref }} -- '*.md')
          else
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              FILES=$(git diff --name-only HEAD^ HEAD -- '*.md')
            else
              FILES=$(git ls-files '*.md')  # If first commit, check all .md files
            fi
          fi
          
          if [ -z "$FILES" ]; then
            echo "No markdown files to validate."
            exit 0
          fi
          
          echo "FILES=$FILES"
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Run Markdown validation
        run: python .github/scripts/validate_markdown.py $FILES
